### ISSUE TITLE
In the footer, the link "company" returns a page not found

### ISSUE THREAD

**Issue by thelinuxfr** [nextcloud/nextcloud.com#100]
In the footer, the link "company" returns a page not found : 

Company > https://nextcloud.com/team/ > Page not found

**Comment by mar1u5** [comment]
Should be live verry soon :grin: THX for your report :facepunch: 

@jospoortvliet

**Comment by jospoortvliet** [comment]
let me disable that until we have the page finished!

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/commit/334c819713a5f6189dfb8c7ecffcde45745bc716
