### ISSUE TITLE
Text is overlapped by background

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/nextcloud.com#1007]
![image](https://user-images.githubusercontent.com/5836855/48936305-d1995b00-ef0a-11e8-9130-73043fc3dd90.png)

https://nextcloud.com/blog/nextcloud-12.0.12-13.0.8-and-14.0.4-are-available/
with Chromium

**Comment by jospoortvliet** [comment]
Not really sure what you mean. The background is transparent so the blue background image shines through. I probably should turn off the transparency, it doesn't look great all the time but it isn't a bug, it was really intentional :grin:
