### ISSUE TITLE
Broken link to bug trackers

### ISSUE THREAD

**Issue by Sauermann** [nextcloud/nextcloud.com#1012]
On https://nextcloud.com/support/ the link to `bug trackers` https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md is broken and returns a 404.

**Comment by jancborchardt** [comment]
The correct link is https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md (moved into `.github` subfolder).

@Sauermann do you want to submit a pull request with the fix? The link is wrong on the support and the contribute page: https://github.com/nextcloud/nextcloud.com/search?q=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fblob%2Fmaster%2FCONTRIBUTING.md&unscoped_q=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fblob%2Fmaster%2FCONTRIBUTING.md

**Comment by Sauermann** [comment]
Can create a pullrequest on weekend.
