### ISSUE TITLE
Security scan not working

### ISSUE THREAD

**Issue by boschkundendienst** [nextcloud/nextcloud.com#1018]
Hi,
I tested now for 2 days to get the security scan to check my instance which worked flawlessly since installation. I host nextcloud via official docker as https://nc.mydomain.de (no subfolder) and the scanner shows no result. Last scan is from 2018-11-10 and any rescans do not bring up new results.

Is there a known issue with the scanner?

Btw. already disabled adblocker - and yes I clicked the rescan button already!

Thanks in advance

Peter

**Comment by Lartza** [comment]
I personally managed to get the site to rescan my instance once (cache from september) but not again after that. So could be some specific scenario it fails in.

**Comment by boschkundendienst** [comment]
I tried now on ios 12.1.1 with Safari and it worked. Shame that it did not work with chrome, chromium firefox (win or linux) neither with ie or edge.
