### ISSUE TITLE
Nextcloud providers - application form

### ISSUE THREAD

**Issue by silvaarapi** [nextcloud/nextcloud.com#1019]
I was checking the application page on the website to get listed as a provider: https://nextcloud.com/providers/apply/ 

Apparently the form does not allow you to enter an organization name which contains numbers as part the name. This error appears: 

> Sorry, there was an error with the form you submited
> Error(s) detected: The organization you entered does not appear to be valid

When entering the name without the numbers, the form was submitted.

**Comment by jospoortvliet** [comment]
Hmmm, ok. We're actually planning to move that entire page to the Nextcloud wiki, so that'll get resolved quite easily that way... Will to that over the coming month or so.
