### ISSUE TITLE
Provider own-box is dead and has broken SSL

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/nextcloud.com#1075]
Looked at German NC providers. And saw this SSL error. The SSL cert is for a domain parking provider.

This does not look good for NCs reputation. I suggest that you automatically check all listed providers for HTTP and SSL errors daily. 

![Bildschirmfoto von 2019-03-27 21-34-58](https://user-images.githubusercontent.com/1377943/55110494-6d64ee80-50d8-11e9-9639-3180a1736724.png)

**Comment by edent** [comment]
Another broken provider

* https://www.wk-it.net

**Comment by tflidd** [comment]
I prepared a PR https://github.com/nextcloud/nextcloud.com/pull/1122



>     * https://www.wk-it.net

This one seems still to be operating, the certificate on his cloud seems to be working. We should probably warn them first.
