### ISSUE TITLE
Web installer

### ISSUE THREAD

**Issue by skaa** [nextcloud/nextcloud.com#1076]
Please update https://download.nextcloud.com/server/installer/setup-nextcloud.php to actual version (now pointing to 15.0.2).

**Comment by jakob-r** [comment]
Also this link does not lead to a download of the real php. All the php content is stripped so it does nothing.

**Comment by wiswedel** [comment]
still pointing to 15.0.2 (by the way: the German version shows 15.0.7)

**Comment by jospoortvliet** [comment]
See https://github.com/nextcloud/nextcloud.com/issues/1076 - I think we have to change the way the web installer works to just always grab either the stable channel or just the latest release. In any case, this is not a website issue...

**Comment by wiswedel** [comment]
> In any case, this is not a website issue...

@jospoortvliet So which is the right repo to open a follow-up issue in? Where's the source for https://download.nextcloud.com/server/installer/setup-nextcloud.php hosted?
