### ISSUE TITLE
Link to Appstore

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/nextcloud.com#108]
Hi in page : https://nextcloud.com/install/?utm_content=bufferd39f6&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#1

the Image [Availabe on the App Store] link to "https://itunes.apple.com/app/id1125420102", It would be more correct "https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8".

look https://linkmaker.itunes.apple.com/en-us/details/1125420102?q=nextcloud&country=us&media=appstore&genre=catalogs

bye
m.

**Comment by jospoortvliet** [comment]
Fixed: https://github.com/nextcloud/nextcloud.com/commit/322cdde83efb7842c25dbf11116ff44ff8e28484
