### ISSUE TITLE
Newest Version of Client is 2.5.2

### ISSUE THREAD

**Issue by Tanarri** [nextcloud/nextcloud.com#1082]
Hi,

on the site https://nextcloud.com/install/#install-clients is the outdated Version 2.5.1 listet.
But the newest Version is https://github.com/nextcloud/desktop/tree/v2.5.2

This should be updated

Greetings
TanarRi

**Comment by MichaIng** [comment]
Also just found that. I opened a PR to update the version strings, including the once for just released server 15.0.6 and beta2: https://github.com/nextcloud/nextcloud.com/pull/1084

**Comment by jospoortvliet** [comment]
@MichaIng thanks a lot! I've merged it. we have 15.0.7 coming tomorrow so I'll deploy after that is in, too!

**Comment by MichaIng** [comment]
@jospoortvliet 
Makes sense, thanks for merging!
