### ISSUE TITLE
Website Broken, No CSS?

### ISSUE THREAD

**Issue by muellert** [nextcloud/nextcloud.com#1090]
At the moment, the website is very, very slow, 
![screen-2019-04-15-09-51-07-nextcloud-website-broken](https://user-images.githubusercontent.com/1183079/56119512-31e57380-5f64-11e9-8be2-575d2ddc12c9.png)
looks quite unstyled and is difficult to use. I tried with both Firefox and Google Chrome.

**Comment by wiswedel** [comment]
@muellert Can this be closed?

**Comment by muellert** [comment]
Yes.
