### ISSUE TITLE
Hardening guide webpage is not available for version 15

### ISSUE THREAD

**Issue by alesnav** [nextcloud/nextcloud.com#1092]
Hi,

It seems that "Hardening guide" webpage does not exist for version 15.

Version 14 is working --> https://docs.nextcloud.com/server/14/admin_manual/configuration_server/harden_server.html

Version 15 reports a 404 not found --> https://docs.nextcloud.com/server/15/admin_manual/configuration_server/harden_server.html

Thanks

**Comment by Lartza** [comment]
The section has been moved

https://github.com/nextcloud/documentation/commit/64d62c64897217e3b701c9964048508f4852f9d4

https://docs.nextcloud.com/server/15/admin_manual/installation/harden_server.html
