### ISSUE TITLE
German server download link outdated (15.0.7 instead of 16.0.0)

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/nextcloud.com#1104]
German Server download page still shows 15.0.7 as latest version: https://nextcloud.com/de/install/#instructions-server
English site already shows 16.0.0

**Comment by wiswedel** [comment]
related: #1076

**Comment by jospoortvliet** [comment]
Ah, the translations. They're messy, the way it works doesn't really take the install page's needs into account. Let me see if I can get that updated soon.

**Comment by jospoortvliet** [comment]
fixed.
