### ISSUE TITLE
Security scan not working

### ISSUE THREAD

**Issue by mehturt** [nextcloud/nextcloud.com#1116]
Re-trigger scan of an existing site does not work, for my site it displays results from 2018. Other people have the same / similar problem: https://help.nextcloud.com/t/nextcloud-security-scan-down/53530

**Comment by Sanookmakmak** [comment]
#meetoo

**Comment by danielb42** [comment]
Can confirm. I am trying to re-trigger the scan since last week.

**Comment by danielb42** [comment]
It's working again.

**Comment by DrDeath** [comment]
Sorry, for me it is not working.
Still: "Scanned at 2019-05-11 07:57:48" , so trigger re-scan from today is not working.

**Comment by phonon112358** [comment]
for me, the security scanner also doesn't work... 
tried it several times.

**Comment by herrmannsdorfer** [comment]
And rescan is down again ...

Related thread in the user forum:

[https://help.nextcloud.com/t/scan-nextcloud-com-again-without-function/57141/8](url)

**Comment by herrmannsdorfer** [comment]
It's working again - at least we got new test results from yesterday.

@mehturt I would recommend closing this issue.

**Comment by mehturt** [comment]
I guess whoever fixed the scan thing should close this.

**Comment by herrmannsdorfer** [comment]
Yes. Or it was fixed without knowledge of this issue? Either way you could help by closing this issue as you started it.

**Comment by FudiHub** [comment]
since 04/2020 Re-Scan isn't working again.
