### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by jenoe** [nextcloud/nextcloud.com#1128]
the blog's RSS feed is broken
at https://nextcloud.com/blog/ there is a RSS icon with a link to https://nextcloud.com/blogfeed/ that redirects to the empty view at https://nextcloud.com/blog/static-feed/

**Comment by gary-kim** [comment]
Just tried the link. It seems like <https://nextcloud.com/blog/static-feed> is working. Does it only work sometimes?

**Comment by jenoe** [comment]
you are right. its working now. i actually tried it in several browsers and it was empty.

**Comment by gary-kim** [comment]
Okay, we can chalk it up to a fluke then.

**Comment by Timvde** [comment]
The feed is empty again. Seems like something is not 100% right.
