### ISSUE TITLE
New Logo Provider

### ISSUE THREAD

**Issue by Aybee2k** [nextcloud/nextcloud.com#113]
Can you change the logo? Something is there with the logo does not run correctly, Color not correct

![logokle](https://cloud.githubusercontent.com/assets/8160220/17871999/6dd743c2-68be-11e6-8e38-44d58e2ceab2.png)

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/commit/ff51603e509f2410fc436f910c6cf867fe0ab705
