### ISSUE TITLE
Ability to Click a 'Phone this number' directly next to contacts

### ISSUE THREAD

**Issue by davepeach1** [nextcloud/nextcloud.com#114]
When viewing my contacts in the browser, specifically on mobile, it would be great to be able to click a link next to number to phone that number. At the moment I copy a paste into into phone app.

Not a problem - more of a nice to have.

**Comment by jospoortvliet** [comment]
Not sure where that would need changes but most likely in the Contacts app - that can be found here: https://github.com/owncloud/contacts
