### ISSUE TITLE
Cannot navigate to other pages in Blog/News

### ISSUE THREAD

**Issue by Ram-Z** [nextcloud/nextcloud.com#1147]
On https://nextcloud.com/blog/, clicking on "Older Posts" gives a blank page.

The href on the button is supposed to go to https://nextcloud.com/blog/page/2 but that seems to redirect to https://nextcloud.com/page/2 which doesn't seem to exists.

**Comment by jospoortvliet** [comment]
Took forever, but I finally figured it out. Broke 50 blogs in the process but those have been fixed too ;-)
