### ISSUE TITLE
help.nextcloud.com - improve color scheme of the header line

### ISSUE THREAD

**Issue by j-ed** [nextcloud/nextcloud.com#1158]
I would like to ask you to change the color scheme of the [Nextcloud help forum](https://help.nextcloud.com) header line. The contrast of the icons is very bad and therefore difficult to see.

![grafik](https://user-images.githubusercontent.com/2572764/64906486-90677700-d6e7-11e9-8fa7-59658d38cb85.png)

**Comment by jospoortvliet** [comment]
Fixed. Some CSS magic in help.nc.c!
