### ISSUE TITLE
symmetric buttons

### ISSUE THREAD

**Issue by ldonis** [nextcloud/nextcloud.com#116]
I think symmetric buttons looks a little bit better.

Actual buttons
![non-symmetric](https://cloud.githubusercontent.com/assets/2887823/17951412/2fb483f4-6a1f-11e6-9be1-2867d79b0be3.png)

Symmetric buttons
![symmetric](https://cloud.githubusercontent.com/assets/2887823/17951699/660ecc5a-6a21-11e6-8218-c9bdc51235f4.png)

What do you think ?

**Comment by Espina2** [comment]
I think its better to. Can you give me some feedback on this

https://github.com/nextcloud/nextcloud.com/issues/117

**Comment by jospoortvliet** [comment]
Yeah, it would be an improvement but it is pure style and yes, I then prefer to go full redesign like @Espina2 has been working on....

**Comment by ldonis** [comment]
We are going to redesign the webpage completely from scratch
