### ISSUE TITLE
scan.nextcloud.com doesn't fully recognize Nextcloud 17

### ISSUE THREAD

**Issue by j-ed** [nextcloud/nextcloud.com#1164]
The security scan shows a warning because the patch level wouldn't be up-to-date although the latest Nextcloud 17 package has been installed. Can someone please have a look on it and fix it:

![grafik](https://user-images.githubusercontent.com/2572764/65991528-c9e10600-e48d-11e9-83a5-8b911817ab69.png)

**Comment by xxKeith20xx** [comment]
I'm not able to get it to run. I also noticed the dates on the page refer to 2018 and the `Find out how you can upgrade to Nextcloud to keep your data secure.` refers to and old version: https://docs.nextcloud.com/server/13/go.php?to=admin-update .

**Comment by j-ed** [comment]
> I also noticed the dates on the page refer to 2018 ...
The date shown is the date of the last security scan. You have to press the **trigger re-scan** button, wait a couple of minutes and refresh the page again to get it updated - so at least this works as expected.

**Comment by xxKeith20xx** [comment]
@j-ed I've tried that a few times now over the past week and don't get an updated scan actually

**Comment by j-ed** [comment]
Thanks for fixing the mentioned problem:

![grafik](https://user-images.githubusercontent.com/2572764/66154611-2b37df00-e61e-11e9-839f-e9d816b5cb6a.png)

@xxKeith20xx I don't know exactly how you're refreshing the page, but I've just repeated the scan and everything works fine now as you can see on the screenshot. BTW, the time is always displayed in GMT.
