### ISSUE TITLE
Desktop client changelog

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#1171]
I can't find a desktop client changelog or link to it on the download page: https://nextcloud.com/install/#install-clients

It was fixed before (https://github.com/nextcloud/nextcloud.com/issues/90) but the page does not exist anymore.

The current client still needs a changelog: https://github.com/nextcloud/desktop/issues/1506

**Comment by jospoortvliet** [comment]
Let's link to this: https://github.com/nextcloud/desktop/releases

At least that is planned to be kept up to date :D
