### ISSUE TITLE
Security re-scan page never updates, even after scan

### ISSUE THREAD

**Issue by jimbolaya** [nextcloud/nextcloud.com#1184]
https://scan.nextcloud.com/ reports the last scan of my site as "Scanned at 2017-07-22 02:28:24" and shows the scan results from that date. If I ask it to "trigger re-scan", I can see in my web server logs, that a number of requests comes from 95.217.53.149. 

However, the results never seem to be updated. If it's helpful I can post the logs from my server for that IP address. One line that seems pertinent might be

`95.217.53.149 - - [04/Nov/2019:10:55:27 -0500] "GET /oc-shib/status.php HTTP/1.1" 302 4593`

**Comment by jimbolaya** [comment]
I fixed access to status.php

I restrict the ability to see status.php in my apache web server, but allow some sites to access it. 

To enable 95.217.53.149 to access it, add the following to the appropriate file (.htaccess or the apache conf or site file defining your nextcloud access.

```
    <Location /status.php>
         Require            ip 127.  95.217.53.149
    </Location>
```
This should allow from 95.217.53.149 and localhost. Of course, if the scanning server IP changes, you'll need to update that IP.

**Comment by mmccarn** [comment]
I had the same issue caused by geofencing in my firewall.  After creating an exception for access to my nextcloud server from 'scan.nextcloud.com' the scans started updating again.
