### ISSUE TITLE
Release Channels: remove or rename "production"

### ISSUE THREAD

**Issue by kesselb** [nextcloud/nextcloud.com#1190]
Please update https://nextcloud.com/release-channels/ and remove or rename the production release channel. 

From Nextcloud 17 the channel is not available without a subscription and is called "enterprise" then: https://github.com/nextcloud/server/pull/15514

**Comment by sunjam** [comment]
Please do not remove the production channel.  Having it is important to users of this open source software, not just paid clients.  **Please consider keeping the production channel available to all users**.

**Comment by tanghus** [comment]
Please tell me you're not "doing an ownCloud"?

**Comment by kesselb** [comment]
It's already done. This issue is about updating the information on nextcloud.com. Feel free to join the discussion at: https://help.nextcloud.com/t/production-channel-removal/64223

Please keep in mind that it's up to you to install a update or not. The release channel will announce the update earlier or later to your instance. Feel free to ignore the notification. To be honest I don't see a big issue here. It's about announcing updates.

_(Please note I'm not affiliated with Nextcloud GmbH and don't take this as official statement)._

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/nextcloud.com/commit/7a142a982f6fb0f0194045e23c89b00cc3c943f6
