### ISSUE TITLE
Small fixes to the enterprise pricing table

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud.com#120]
We need a few fixes to the pricing table to make it clearer.

* Replace dashes with crosses
* Add the word users to tiers to make it clearer

So it would look something like this:

<img width="609" alt="tiered_pricing" src="https://cloud.githubusercontent.com/assets/323220/18054281/7bbb7612-6e03-11e6-87b9-f5e1511939d1.png">

@jospoortvliet @karlitschek

**Comment by karlitschek** [comment]
makes sense

**Comment by Espina2** [comment]
Im right now design new tables for the the entreprise page. I will post it soon.

**Comment by jospoortvliet** [comment]
@Espina2 is doing great work which will make this much better but for now, a quick fix...

https://github.com/nextcloud/nextcloud.com/commit/56fcd76e74748b2253dc5509b039ed6ad17ca11c

**Comment by jospoortvliet** [comment]
@Espina2 is doing great work which will make this much better but for now, a quick fix...

https://github.com/nextcloud/nextcloud.com/commit/56fcd76e74748b2253dc5509b039ed6ad17ca11c
