### ISSUE TITLE
Turn off Autoplay of Video on https://nextcloud.com Home page

### ISSUE THREAD

**Issue by 0lzi** [nextcloud/nextcloud.com#1221]
Steps to reproduce: Visit https://nextcloud.com on desktop browser ( Vivaldi, Chrome, doesn't seem to happen on Firefox on Android )

Behaviour: Ears blown off by video off screen, which involves me either muting the tab or scrolling down to the video and pausing it.

Expected behaviour: I scroll down page and play video if i want to.

**Comment by chk1** [comment]
Same on the Hub page at https://nextcloud.com/hub/

**Comment by kesselb** [comment]
Seems to be fixed.
