### ISSUE TITLE
scan.nextcloud.com doesn't fully recognize Nextcloud 18

### ISSUE THREAD

**Issue by j-ed** [nextcloud/nextcloud.com#1225]
The security scan shows a warning because the patch level wouldn't be up-to-date although the latest Nextcloud 18 package has been installed. Can someone please have a look on it and fix it:

![grafik](https://user-images.githubusercontent.com/2572764/72678471-8d6e0000-3aa6-11ea-9f77-e5ff52454a89.png)

**Comment by JSoko** [comment]
Same here; seams that the scanner doesn't know 18.0-0-10 yet...

**Comment by donvipre** [comment]
Is this still relevant? Worked for 18.0.3 and 18.0.4 Yesterday for 2 different servers.

**Comment by j-ed** [comment]
You're right, the problem has has been solved in the meantime.
