### ISSUE TITLE
Security scan shows incorrect version of Nextcloud

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/nextcloud.com#1226]
Hi all,

When I perform a security scan of my Nextcloud, it always shows me a very old version of it.

![image](https://user-images.githubusercontent.com/9272078/72679778-c3b17c80-3ab2-11ea-8688-e3bde03652e0.png)

Do you know how this works? My actual version is 17.0.2.

**Comment by JSoko** [comment]
Try "trigger rescan" and look back 3 Minutes later...
![grafik](https://user-images.githubusercontent.com/5583290/72684288-94653480-3adf-11ea-829a-09d36060c99c.png)

**Comment by armaccloud** [comment]
> Try "trigger rescan" and look back 3 Minutes later...
> ![grafik](https://user-images.githubusercontent.com/5583290/72684288-94653480-3adf-11ea-829a-09d36060c99c.png)

Thanks @JSoko
