### ISSUE TITLE
demo.nextcloud.com - SSL cert has expired

### ISSUE THREAD

**Issue by danielkoch** [nextcloud/nextcloud.com#1227]
## Network error
`NET::ERR_CERT_DATE_INVALID`

## Cert details
<img width="481" alt="demo nextcloud com" src="https://user-images.githubusercontent.com/142055/72686783-6dffc300-3af8-11ea-9b7c-a873a4e0d4f7.png">

**Comment by tflidd** [comment]
Someone has fixed this in the meantime independently from this bug report. Anyhow, thank for reporting it.
