### ISSUE TITLE
Site for Flow

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#1230]
I was expecting something to be at https://nextcloud.com/flow

Maybe just copy over the content of the blog at https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/? Or did I miss the actual subsite (which should be /flow, no?)

**Comment by jospoortvliet** [comment]
we have nextcloud.com/workflow already, I'll make 'flow' redirect there.
