### ISSUE TITLE
Typo on scan.nextcloud.com

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/nextcloud.com#1231]
# Our recommendation
We strongly recommend to keep a private cloud server constantly updated. Servers not running the latest security update in a supported release series are often vulnerable. You can find new versions here for Nextcloud and here for ownCloud. Nextcloud strives to make upgrading a safe, easy and painless procedure. As a result of these ~~efforst~~ **efforts**, for users running PHP 7.x and a current version of Nextcloud, there is no need to re-enable apps upon upgrade and users get notified of new versions of apps as well. More improvements are coming! You can learn why and how to upgrade to the latest version of Nextcloud in our earlier blog.

**Comment by GlenCooper** [comment]
Ummm... where are you seeing that typo?  I'm not seeing it on scan.nextcloud.com, or on either historical screenshot of it either in https://archive.vn/https://scan.nextcloud.com/    (although it could have been there at one time when the state of the page wasn't captured by the archiver).

**Comment by GlenCooper** [comment]
Ummm... where are you seeing that typo? I'm not seeing it on https://scan.nextcloud.com, or on either historical screenshot of it either in https://archive.vn/https://scan.nextcloud.com/ (although it could have been there at one time when the state of the page wasn't captured by the archiver).

**Comment by jospoortvliet** [comment]
tnx, found and fixed it, should go live once admins do a deploy.
