### ISSUE TITLE
Replace Google+ share link with an active social network

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/nextcloud.com#1236]
Regarding these social medie share buttons, like in https://nextcloud.com/blog/17-0-3-and-16-0-8-out-now/

![grafik](https://user-images.githubusercontent.com/5323995/73594009-5b2eba80-450a-11ea-938e-7096edc57f55.png)

Google+ has been cancelled. 
Could you replace it with...... Mastodon for example? :-)

**Comment by jospoortvliet** [comment]
Now links to mastodon - https://github.com/nextcloud/nextcloud.com/commit/cd41035a8caacbc4d4cf55913800f6549da01220
