### ISSUE TITLE
Desktop Client for Nextcloud

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/nextcloud.com#125]
Hi, How about a desktop client for the NextCloud Server to be able to connect not only from mobile devices to the server, but from the desktop as well!

regards, hitam4450

**Comment by zeugmatis** [comment]
I believe this already exists on the [download page](https://nextcloud.com/install/) - bottom right side of page under "Get Involved": 

<img width="412" alt="screen shot 2016-09-05 at 10 34 08 am" src="https://cloud.githubusercontent.com/assets/2687584/18254640/91d416ba-7354-11e6-8bed-c3afce463e7a.png">

**Comment by MariusBluem** [comment]
These are the RCs 😁 You will find the released clients here: https://nextcloud.com/install/#install-clients

**Comment by hitam4450** [comment]
Thanks a lot for your guidance!
regards, hitam4450
