### ISSUE TITLE
<title> of the threat model page is "threat-model - Nextcloud"

### ISSUE THREAD

**Issue by strugee** [nextcloud/nextcloud.com#1265]
It should be "Threat model - Nextcloud" instead. I would send a PR but I was unable to determine where `<title>`s are actually defined in this codebase? If anyone knows where and wants to point me to it I'd be happy to send a patch, or someone can just do it themselves.

Cheers!

**Comment by jospoortvliet** [comment]
Sadly this is still defined in Wordpress - may it die soon. I've fixed it, thanks!! @strugee appreciate the help.

**Comment by strugee** [comment]
Thank you!! :tada:
