### ISSUE TITLE
changelog for 18.0.4

### ISSUE THREAD

**Issue by r2evans** [nextcloud/nextcloud.com#1278]
18.0.4 was released yesterday on the blog and on hub.docker.com, but https://nextcloud.com/changelog/ still shows only 18.0.3. Thank you!

**Comment by r2evans** [comment]
Sure, but from 5 seconds ago ...

![image](https://user-images.githubusercontent.com/5815808/80289633-a5cc6700-86f4-11ea-8b7d-bf55ac9c36f2.png)

**Comment by kesselb** [comment]
I guess someone has to deploy the changelog update. In the meantime check https://github.com/nextcloud/nextcloud.com/blob/master/page-changelog.php for the changes.

**Comment by donvipre** [comment]
@kesselb: Do you know who could do this? To be honest, the source code philosophy at the nextcloud.com repository appears a bit unclear to me.

**Comment by kesselb** [comment]
I guess @jospoortvliet or @nextcloud/infrastructure

**Comment by r2evans** [comment]
Looks like it has since been updated, thanks.
