### ISSUE TITLE
Feature request: enhancing API to have trash-bin support in iOS app

### ISSUE THREAD

**Issue by croessner** [nextcloud/nextcloud.com#128]
Hi,

I opened a whishlist feature in the forum:

https://help.nextcloud.com/t/wishlist-trash/3049/2

I was asked to open a ticket for this :-)

Would be cool to enhance the API so that mobile apps like the one for iOS can implement a trash-bin

**Comment by MariusBluem** [comment]
You are requesting an API for the **trash bin** (...which makes sense :wink). This repository is about the Website "nextcloud.com" ... The right place for this request would be the repository of the server 😁 ... I've just copied over for you: https://github.com/nextcloud/server/issues/1332
