### ISSUE TITLE
"nobugs IT GmbH" link is outdated (404)

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/nextcloud.com#1281]
On page: https://github.com/nextcloud/providers the link to "nobugs IT GmbH" seems to be outdated.

**Comment by jospoortvliet** [comment]
This belongs in that repo, it's no longer on the website ;-)

Anyone can do a PR to fix it...

**Comment by jospoortvliet** [comment]
(seems there whole website is down... I'll just get rid of them)
