### ISSUE TITLE
Touch favicon uses same image as regular favicon, leading to blurry display

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#1287]
The normal shortcut icon and `apple-touch-icon-precomposed` refer to the same image:
```
<link rel="shortcut icon" href="https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png?x53054" />
<link rel="apple-touch-icon-precomposed" href="https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png?x53054" />
```

This leads to the favicon showing up blurry in e.g. Nextcloud Mail when compared to other sites. It’s also the case for the help.nextcloud.com forum:
![image](https://user-images.githubusercontent.com/925062/82688570-62183f00-9c59-11ea-97cd-6400148895a7.png)

Instead what should be used is this [favicon-touch.png](https://github.com/nextcloud/server/blob/master/core/img/favicon-touch.png):
![](https://raw.githubusercontent.com/nextcloud/server/master/core/img/favicon-touch.png)

cc @jospoortvliet since it looks like you have to upload it to Wordpress in order for it to work?

**Comment by jospoortvliet** [comment]
I dunno where you found that link, but you can do a simple PR to change it as in that same folder is a file called favicon-touch.png:
https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon-touch.png

Nah, let me do it, you probably just inspected the website ;-)

**Comment by jancborchardt** [comment]
> Nah, let me do it, you probably just inspected the website ;-)

That’s what I did, thanks for the fix! :)
