### ISSUE TITLE
https://nextcloud.com/changelog/ not updated before Nextcloud indicates update available

### ISSUE THREAD

**Issue by xxKeith20xx** [nextcloud/nextcloud.com#1292]
When I see an update available in Nextcloud, I like to parse the changelog first to see what to expect. I've noticed over the past year that there is typically a significant delay between the release of a new version and the changelog appearing on https://nextcloud.com/changelog/ .

Because the online updater links to https://nextcloud.com/changelog/ for more information, I think this page should be populated with the changelog before the updates are available or released in sync.

**Comment by gary-kim** [comment]
That is an issue we sometimes have. If it helps for the purposes of your script, the changelog is generated with this script:

<https://github.com/nextcloud/github_helper#changelog-generator>

**Comment by r2evans** [comment]
"Hub 20" was released at `"2020-10-03T08:30:49+00:00"`, still no changelog. Is there a human release-checklist or CI/CD pipeline that could help automate this step?
