### ISSUE TITLE
Q&A hangout sticker overlapping main title and content

### ISSUE THREAD

**Issue by vincchan** [nextcloud/nextcloud.com#13]
During review of #12 I noticed that the hangout sticker overlaps the main slogan at 964px window width. Content is also covered at other window widths. Is this intended behaviour? @jancborchardt 

### at 700-767px
<img width="705" alt="screen shot 2016-06-10 at 14 26 23" src="https://cloud.githubusercontent.com/assets/868272/15964591/9a277c00-2f19-11e6-8a51-5b24f7ee09fb.png">
---
### at 767-861px 
<img width="844" alt="screen shot 2016-06-10 at 14 26 53" src="https://cloud.githubusercontent.com/assets/868272/15964594/9cf1d9b2-2f19-11e6-975e-fc9553a964a1.png">
---
### at 935-991px
<img width="971" alt="screen shot 2016-06-10 at 14 27 15" src="https://cloud.githubusercontent.com/assets/868272/15964603/a6065014-2f19-11e6-989e-8dbfd2b93f15.png">

**Comment by jancborchardt** [comment]
@vincchan it’s not indended. :) Do you want to jump in and fix it?

**Comment by vincchan** [comment]
@jancborchardt alright I'll have a look at it

**Comment by jospoortvliet** [comment]
fascinating, I absolutely can't reproduce ;-)

What browser is that?

**Comment by vincchan** [comment]
@jospoortvliet media query was targeting 1.5 pixel ratio
