### ISSUE TITLE
Spelling error on nextcloud.com front page

### ISSUE THREAD

**Issue by GlenCooper** [nextcloud/nextcloud.com#1316]
Commodity is misspelled as "comodity". Makes someone like me think if you have spelling errors on your front page, what else is wrong in the code? Please fix. Thanks.
![85622606-a03cc000-b656-11ea-96f6-6358b1a7480b](https://user-images.githubusercontent.com/967793/86505487-d267c380-bdb4-11ea-9c67-75f0a155f805.png)

**Comment by tflidd** [comment]
Fixed in https://github.com/nextcloud/nextcloud.com/pull/1315

**Comment by GlenCooper** [comment]
Confirmed fixed.  https://archive.vn/jdxhr

**Comment by GlenCooper** [comment]
I recently learned that it's possible to highlight something in a page that has been archived by archive.vn, and the URL in your browser's URL bar will automatically update to a URL with proper anchors to reproduce that highlit section later on.

In this case; https://archive.vn/jdxhr#selection-5087.52-5087.61
