### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by marado** [nextcloud/nextcloud.com#1318]
At https://nextcloud.com/talk/ , on the footer, there is a link for "bug tracker", pointing to https://docs.nextcloud.com/server/latest/developer_manual/bugtracker , which leads to a 404.

**Comment by thebencourt** [comment]
There's also a link on https://nextcloud.com/contribute/ (Get a bug fixed: bugtracker documentation) which links to the same page.
At a guess they should be pointing to: https://docs.nextcloud.com/server/latest/developer_manual/prologue/bugtracker/
