### ISSUE TITLE
RSS feeds can't be discovered

### ISSUE THREAD

**Issue by PeterHagen** [nextcloud/nextcloud.com#1327]
I noticed that the RSS feed of the blog can be found by clicking a small rss logo on the [blog](https://nextcloud.com/blog/) page:

<img width="720" alt="Screenshot 2020-07-28 at 08 17 45" src="https://user-images.githubusercontent.com/12300899/88626403-dda7c980-d0aa-11ea-9551-d345edc7e0e5.png">

it would be great if the rss, and preferable all RSS feeds, can be discovered through the header. Just adding something like this in head would fix it:

```
<link rel="alternate" type="application/rss+xml" href="/blogfeed" title="The latest updates">
```

**Comment by jospoortvliet** [comment]
thanks, good catch!
