### ISSUE TITLE
Nextcloud Security Scan won't trigger re-scan

### ISSUE THREAD

**Issue by stefanheijnen** [nextcloud/nextcloud.com#1330]
Somehow my host is stuck in 2018. Re-trigger scan doesn't work. I've been trying this for the past 2-3 months. I think it is safe to say it doesn't work. How can I fix this?

![image](https://user-images.githubusercontent.com/1306331/89096081-d4349f00-d3d3-11ea-8d51-a66cacd8f893.png)

**Comment by jospoortvliet** [comment]
So first, check if [your server address]/status.php can be reached. If not - fix that, your server is broken. If it is, tell me the address of your server and our sysadmins can have a look ;-)

**Comment by stefanheijnen** [comment]
I found the issue. I'm using pfSense + pfBlockerNG as firewall solution. pfBlockerNG is configured to use GeoIP data by MaxMind Inc. Apparently scan.nextcloud.com (95.217.53.149) is in the Top Spammers database (pfB_Top_v4). I've whitelisted it and it is working again.

**Comment by ozinfotech** [comment]
I'm getting the same issue where a rescan appears to be triggered, but doesn't actually do it. I checked on the _status.php_ file from an off-network device and it shows this:

`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"20.0.0.9","versionstring":"20.0.0","edition":"","productname":"In the Cloud","extendedSupport":false}`

**Comment by jospoortvliet** [comment]
> I'm getting the same issue where a rescan appears to be triggered, but doesn't actually do it. I checked on the _status.php_ file from an off-network device and it shows this:
> 
> `{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"20.0.0.9","versionstring":"20.0.0","edition":"","productname":"In the Cloud","extendedSupport":false}`

Then give me the URL and I'll ask our sysadmins (if it still doesn't work).

**Comment by ozinfotech** [comment]
> > I'm getting the same issue where a rescan appears to be triggered, but doesn't actually do it. I checked on the _status.php_ file from an off-network device and it shows this:
> > `{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"20.0.0.9","versionstring":"20.0.0","edition":"","productname":"In the Cloud","extendedSupport":false}`
> 
> Then give me the URL and I'll ask our sysadmins (if it still doesn't work).

@jospoortvliet, I still have the issue. The URL is cloud.osawatomieks.org.

**Comment by jospoortvliet** [comment]
Ah, makes sense, Cloudflare and other stuff ofc might block our scanner ;-)
