### ISSUE TITLE
Nextcloud Conference 2020 page title

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#1338]
Hey Jos,

the virtual 2020 conf sounds great. Only a small nitpick about the conf page. The page title is not correctly set.

![Page title](https://user-images.githubusercontent.com/1869584/90490531-06b5fa00-e13f-11ea-9ce1-9f69c4234968.png)

**Comment by jospoortvliet** [comment]
fixed! Thanks.
