### ISSUE TITLE
Add new provider error - The link to an image you entered does not appear to be valid.

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/nextcloud.com#135]
I just tried to submit IndieHosters to the list of providers, but I get this error:

The link to an image you entered does not appear to be valid.
Here is the image:  https://indie.host/indiehosters.png

**Comment by MariusBluem** [comment]
I see that you are listed now, so the problem seems to be solved for you 😉 ... 

<img width="426" alt="bildschirmfoto 2017-01-30 um 13 36 56" src="https://cloud.githubusercontent.com/assets/19711361/22423294/318186c4-e6f1-11e6-961f-99b0d1e08831.png">

**Comment by pierreozoux** [comment]
Yes, sorry, forgot to close, thanks!
