### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by toweih** [nextcloud/nextcloud.com#1368]
@nextcloud-pr-bot 
Your website nextcloud.com stalls on loading web-ressources for 30secs, tiny things like fonts.
![image](https://user-images.githubusercontent.com/19357553/95119687-a6116980-074c-11eb-80c9-653be967cbb9.png)
Tobi

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

I guess the servers are back again.

**Comment by Skywalker-11** [comment]
Issue seems to be back. Eg some resources of https://apps.nextcloud.com stall for 30-60s and download.nextcloud.com downloads transfers the updates with ~60-110kB/s. 
Download of the update (~110MB) thus results to ~20Min download time :disappointed:
