### ISSUE TITLE
Fix https://nextcloud.com/box/ layout - small task, need help!!!

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#137]
![spectacle wz1437](https://cloud.githubusercontent.com/assets/551757/18599381/880462ae-7c58-11e6-8f17-6827d0ac6afa.png)
That is horrible... And I have no time to fix it, help welcome!

**Comment by Espina2** [comment]
Hi, Jos you can easy fix this if you have a drop inside on the button, consider this example ( Its just a quick tip)

http://foundation.zurb.com/sites/docs/v/5.5.3/components/dropdown_buttons.html

If you want I can think and design a better page, and if anyone can send me the box (no need the hardrive) I can take better product photos. :)

**Comment by MariusBluem** [comment]
@Espina2 could you open a PR 😁

**Comment by Espina2** [comment]
@MariusBluem How I do that? Can you do it or teach me? ;)

**Comment by MariusBluem** [comment]
- Navigate to the `page-box.php` file (here: https://github.com/nextcloud/nextcloud.com/blob/master/page-box.php)

- Click on the small pencil (Edit this file) 

- Edit the file (remove the buttons and add your dropdown with the links)

- Type in a title for your commit ("Fix #137" would be a nice one ;) ... Describe what you have done (Don't write a big novel for such changes)

- Click on "Create a **new branch* ... and type in `fix-137` (or something...) as branch-name

- Click "Propose file change" ... And then ... open the PR 🚀 

If you have any questions - feel free to ask 😉

**Comment by Espina2** [comment]
@MariusBluem sorry, I didn't understood first when you asked for the PR, but for your answer now I can see that you wanted me to change the actual code and I can't do that because I'm a designer, not a coder. :) I was only trying to show you an easy way for you to do that because that site has examples with documentation.

**Comment by MariusBluem** [comment]
Thats also my problem 😅 @Espina2 ... I will try 😉
