### ISSUE TITLE
Changelog link is not easy to find

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud.com#1371]
I got a report that the changelog is very hard to find on our webpage. Maybe we can put a link additionally to https://nextcloud.com/install/

cc @jospoortvliet

**Comment by jospoortvliet** [comment]
That's where it is:
![Screenshot_20201126_131130](https://user-images.githubusercontent.com/551757/100349551-ed97d180-2fe8-11eb-8db9-0493be6354d3.png)

**Comment by jospoortvliet** [comment]
If you have ideas for a better location, let me know - but I don't think I can make it much more clear than directly next to the version number...
