### ISSUE TITLE
New podcast epidoses not available on Spotify

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#1377]
Hey @jospoortvliet,

the last podcast episode from The Nextcloud Podcast on Spotify is from august. Is there any reasom for that or did you (or someone else 😄) just forgot to upload it there? Would love to hear the new epiaodes on Spotify.

**Comment by jospoortvliet** [comment]
That seems a mistake, yes, let me look into it.

**Comment by jospoortvliet** [comment]
@Itsavar can you check this?

**Comment by ltsavar** [comment]
@jospoortvliet you mention the wrong person ;)
One Episode is indeed missing on spotify. I don't know why. I checked everything.
