### ISSUE TITLE
Renew certificate for download.nextcloud.com

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#1384]
@jospoortvliet Your certificate expired on download.nextcloud.com

https://help.nextcloud.com/t/zertifikat-abgelaufen/96976

**Comment by dartcafe** [comment]
As well as https://docs.nextcloud.com/

**Comment by rakekniven** [comment]
> 
> 
> As well as https://docs.nextcloud.com/

Works for me.

**Comment by rakekniven** [comment]
Works now!

**Comment by nickvergessen** [comment]
I didn't fix it. The cert is auto renewed. It just seems that the apache has a bug which makes the reload/restart not work

**Comment by ReinerNippes** [comment]
https://www.google.com/search?q=certificate+monitoring
