### ISSUE TITLE
download.nextcloud.com about to expire soon

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#1410]
The SSL certificate of download.nextcloud.com is about to expire soon (in 5 days). The certbot normally renews when it is less than 30 days...
@nextcloud/infrastructure

**Comment by rullzer** [comment]
Gives march3 for me.... but I'll keep an eye on it

**Comment by tflidd** [comment]
@rullzer : Again, it is about to expire this Wednesday (less than 48h)!
