### ISSUE TITLE
help.nextcloud.com problem with SSL & ipv6

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#1411]
Since at least today, there is an issue with the forum to connect via ipv6:

```
curl -v https://help.nextcloud.com
* Rebuilt URL to: https://help.nextcloud.com/
*   Trying 2a01:4f9:2b:29dc::146...
* TCP_NODELAY set
* Connected to help.nextcloud.com (2a01:4f9:2b:29dc::146) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to help.nextcloud.com:443
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to help.nextcloud.com:443 

```

SSL labs shows a problem as well:
https://www.ssllabs.com/ssltest/analyze.html?d=help.nextcloud.com

![grafik](https://user-images.githubusercontent.com/8111200/103386037-3b7a8a80-4afd-11eb-9f52-cb0ebfec3fa5.png)

@nextcloud/infrastructure

**Comment by tflidd** [comment]
The complaints start to pile up:
https://help.nextcloud.com/t/help-nextcloud-com-with-firefox-pr-end-of-file-error/95412/16
https://help.nextcloud.com/t/problems-with-forum-from-firefox-manjaro-xfce/103077
https://help.nextcloud.com/t/help-nextcloud-com-via-ipv6-has-not-tls/103016
https://help.nextcloud.com/t/https-help-nextcloud-com-t-ist-nicht-erreichbar-unter-firefox/102793

@jospoortvliet Can you find somebody to fix this soon?

**Comment by nickvergessen** [comment]
Forwarded internally

**Comment by nickvergessen** [comment]
Should be fixed now

**Comment by brknkfr** [comment]
> Should be fixed now

Really? In the last two days I'm still suffering from the same problem. (Gnome-Shell 3.36.7 with Mozilla Firefox 78.7.1esr or Epiphany on a gentoo system).

**Comment by jospoortvliet** [comment]
Arthur had another fun few days of fighting with help.nextcloud.com and reports it as fixed...

**Comment by caemor** [comment]
Same problem seems to be back again:
https://www.ssllabs.com/ssltest/analyze.html?d=help.nextcloud.com&latest

This also seems to be the issue why I can't open the help page with firefox currently (PR_END_OF_FILE_ERROR)

**Comment by Chartman123** [comment]
Seems to happen again... Can't connect via IPv6 since yesterday. 🙈

**Comment by tflidd** [comment]
@jospoortvliet can you send the ipv6 firefighters again? In some regions, ipv6 is already up at 50%...

**Comment by tflidd** [comment]
It's working again.
