### ISSUE TITLE
Link to Demo in site header

### ISSUE THREAD

**Issue by nina-py** [nextcloud/nextcloud.com#1412]
Is there any reason the link to the demo in the site header is https://demo.nextcloud.com/ instead of https://try.nextcloud.com/ where the user eventually ends up after a redirect? The redirect is not instant and the page at `demo.nextcloud.com` is unstyled so that it looks like there is a flash of unstyled content before `try.nextcloud.com` loads.

**Comment by jospoortvliet** [comment]
ah. Yes, this move to try.nextcloud.com, no idea why that was done... let me just update the link. Thanks!
