### ISSUE TITLE
The link to "general guidelines and setup" is not correct

### ISSUE THREAD

**Issue by camilasan** [nextcloud/nextcloud.com#1422]
In the page https://nextcloud.com/contribute/, the link in "general guidelines and setup" points to https://docs.nextcloud.com/server/latest/developer_manual/general, which shows:

![notfound](https://user-images.githubusercontent.com/241266/104731636-4d367180-573c-11eb-9305-6c31616306bf.png)

https://github.com/nextcloud/nextcloud.com/blob/cc8e2b547d6a508a0d8fe65b597e2637663ebd12/page-contribute.php#L36

**Comment by jospoortvliet** [comment]
Sigh. They keep re-ordering stuff in the documentation, which breaks links... found the right one, will update the link. but it'll break again next time they re-order things :(
