### ISSUE TITLE
Certificate expired for https://usercontent.apps.nextcloud.com

### ISSUE THREAD

**Issue by darkblaze69** [nextcloud/nextcloud.com#1436]
Certificate expired for usercontent.apps.nextcloud.com on 29.01.2021.
So icons for Apps not loading

**Comment by kesselb** [comment]
I don't see an expired certificate. But some screenshots have content-lenght 0 (e.g files_accesscontrol).

cc @nextcloud/infrastructure

**Comment by darkblaze69** [comment]
ok, now the certificate for https://usercontent.apps.nextcloud.com is fixed

**Comment by rullzer** [comment]
Yep all done :)
