### ISSUE TITLE
CTA buttons don't appear on enterprise page for non-desktop view

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/nextcloud.com#1445]
@jospoortvliet Just filing this as a reminder for the CTA buttons at https://nextcloud.com/enterprise/ which don't appear for table + mobile view. (e.g. "Get a quote")

**Comment by jospoortvliet** [comment]
fixed in https://github.com/nextcloud/nextcloud.com/commit/2edeab580d8bb897fedd836bc9004251708e5e6b
