### ISSUE TITLE
Fix menu layout of docs.nextcloud.com

### ISSUE THREAD

**Issue by coderkun** [nextcloud/nextcloud.com#145]
The subdomain [docs.nextcluod.com](https://docs.nextcloud.com) has a different menu (styling and order of items):

![nc-news](https://cloud.githubusercontent.com/assets/5249815/18809955/48157a42-828a-11e6-98de-80b1ed69cf5d.png)
![nc-docs](https://cloud.githubusercontent.com/assets/5249815/18809956/49f86a86-828a-11e6-8b78-0324f53dcc52.png)

Both menus should at least look the same. Maybe there is also a way to actually use the same menu (logic/template).

**Comment by jospoortvliet** [comment]
so we have to fix this, yes. Sadly the code is entirely different - it can be found here: https://github.com/nextcloud/documentation/tree/master/_shared_assets/themes/nextcloud_release

I will have to update this as we've just introduced a new drop-down menu header which is quite nice and pretty but simply not available on the documentation site.

**Comment by Espina2** [comment]
This should be easy right?

**Comment by jospoortvliet** [comment]
It isn't hard, it is stand-alone code. But you have to set up the documentation, install sphinx and all that - to test it. It just takes time which, at the moment, I don't have - I want to clean the rest of my 1200 notifications in github and the forums and I have to review a doc and write some blogs and... ;-)

**Comment by MariusBluem** [comment]
Issue in documentation --> https://github.com/nextcloud/documentation/issues/244
Would be nice if one of you two (@jospoortvliet or @Espina2) could fix this 😅
