### ISSUE TITLE
Nextcloud-Security-Scan - Version 21.0.0.18 not recognized as latest patch level, impacting rating

### ISSUE THREAD

**Issue by bf8392** [nextcloud/nextcloud.com#1458]
As stated above, the security-scanner doen't seem to recognize the Version 21 as the latest which impacts the security-rating...as this version is extremly new, I suspect a missing database-enty in the security-scanner...

**Comment by jospoortvliet** [comment]
I've made some changes, will need a techie to review & deploy but then it's hopefully fixed soon. This is still a manual process which means the scanner is almost always outdated :cry:
