### ISSUE TITLE
Nextcloud Box Photos

### ISSUE THREAD

**Issue by Espina2** [nextcloud/nextcloud.com#147]
I will post here some photos of the box. You can choose what is better and for what to change in the page you have now. 

What do you think about the photos?

Anyway I will post it a new page soon to. 

![nextcloud-box-perspective](https://cloud.githubusercontent.com/assets/11150206/18827793/832ebcfe-83cc-11e6-84bf-137562387fc8.png)

![nextcloud-box](https://cloud.githubusercontent.com/assets/11150206/18827792/832db2b4-83cc-11e6-9208-2143ee4c8e8c.png)

![box-opne](https://cloud.githubusercontent.com/assets/11150206/18831506/f16cac56-83dd-11e6-9dde-bc9c116c4112.png)

**Comment by jospoortvliet** [comment]
The third - I suggest you connect the last cable, too, the one which goes into the Pi (it is now loose). Then it makes for a nice image. See the current website: I took a pic of the accessories, but perhaps you can do better.

**Comment by Espina2** [comment]
I agree with you in the third one. I have more pictures but I didnt do the after effects and corrections. I thinking im do a video like the first picture with the raspberry pi turn on because it have a very nice white light.

**Comment by oparoz** [comment]
Awesome work :)

I have a slight concern about the 1st picture, there is something strange going on between the perspective of the box and the logo. It's probably an optical illusion, but maybe we could use a slightly different angle?

**Comment by Espina2** [comment]
Now that you say, when I look at the picture I saw what you are talking about it. I dont know if are because of the printing or another thing.

**Comment by jancborchardt** [comment]
Nice work! :) Another issue with the first picture is that you never really see the box this way. Even though the picture on https://nextcloud.com/box/ needs to be of better quality, the perspective is good and how you see it usually.

Would be cool to get a shot of it similar to that perspective. And then one in that perspective but open. Then we can also do this Mac Pro animation stuff we talked about. ;)

**Comment by Espina2** [comment]
Yup I already have all the pictures but need to post product them, I have in another perspectives just only no time to do nothing beside coding the new homepage and enterprise. :)

**Comment by jancborchardt** [comment]
Cool, no rush! :)

**Comment by MariusBluem** [comment]
Page is now up and running with nice photos. Closing here 😉
