### ISSUE TITLE
Error: Request could not be executed on help.nextcloud.com

### ISSUE THREAD

**Issue by Phaeton20** [nextcloud/nextcloud.com#1470]
https://help.nextcloud.com/t/how-to-remove-add-notes-lists-or-links/70977

Error: Request could not be executed

The network protocol was violated when loading the page https://help.nextcloud.com/t/how-to-remove-add-notes-lists-or-links-from-folders-workspaces/71038. This error cannot be corrected.

The page you are trying to view cannot be displayed because a data transfer error was detected.

     Please contact the website owners to notify them of this problem.

**Comment by kesselb** [comment]
I'm not able to reproduce.
