### ISSUE TITLE
Top-Menu should stick at the right side 

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/nextcloud.com#15]
With Safari on my iPad Pro 9.7: 

![image](https://cloud.githubusercontent.com/assets/19711361/15970561/7456ba9c-2f35-11e6-9aeb-f64d029a30fd.png)

**Comment by jancborchardt** [comment]
Yeah, good point. That also happens on smaller sizes on desktop. Tagging as a good starter issue, anyone up for checking that out @nextcloud/designers? :)
