### ISSUE TITLE
Add a link to the changelog on the download page

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud.com#153]
Other companies:

```
Latest stable version: 9.1.1
See what's new (Changelog)
```

Also I miss an easy way to get the 9.0.54 update. Other companies have a link:

```
Looking for older versions or major releases?
```

Would be nice if we can add those as well somehow.

**Comment by Espina2** [comment]
I will think on that as soon I jump in to design this page. :)

**Comment by MariusBluem** [comment]
We have it (now) 😜

<img width="1134" alt="bildschirmfoto 2017-01-30 um 13 34 19" src="https://cloud.githubusercontent.com/assets/19711361/22423243/fb63caf2-e6f0-11e6-8ffd-57829a8c1eb3.png">
