### ISSUE TITLE
A background image is awfully made up.

### ISSUE THREAD

**Issue by Scottpedia** [nextcloud/nextcloud.com#1559]
On the project's [web page](https://nextcloud.com/collaboraonline/), the background image shows a user on a Windows 10 operating system using Mozilla Firefox running in a Ubuntu GUI environment with no clear signs of a VM present. On the task bar, it's shown that only Skype and screenshot utility are opened. 

Well it's not really a serious error, but I don't think this kind of mistake is tolerable in the tech industry...

![screenshot](https://nextcloud.com/wp-content/themes/next/assets/img/headers/collabora.jpg?x53054)

**Comment by splitt3r** [comment]
Duplicate of https://github.com/nextcloud/nextcloud.com/issues/1507

**Comment by acsfer** [comment]
Closing as duplicate of https://github.com/nextcloud/nextcloud.com/issues/1507
