### ISSUE TITLE
Remove CAPTCHA from newsletter signup

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#156]
Since there is an email confirmation link sent anyway, the CAPTCHA is just annoying.

**Comment by chrisjimallen** [comment]
Hi, the newsletter link is https://newsletter.nextcloud.com/?p=subscribe&id=1, which is not in the repo, so I'm guessing this one can't be completed by external contributors? 

If I'm wrong, please advise and I'll be happy to help.

**Comment by jancborchardt** [comment]
@chrisjimallen yeah, I think it’s something only in the phpList admin interface which @jospoortvliet and maybe @LukasReschke have access to.

You are very welcome to help with other aspects though! :)

**Comment by LukasReschke** [comment]
We can disable that in PHPList but you'll end up with a lot of spam subscriptions due to people on HackerOne running scanners. If we can live with some people complaining … sure … 

@jospoortvliet Your call. ;)

**Comment by jancborchardt** [comment]
@LukasReschke but they need to confirm their email anyway by clicking a link. That’s already the mechanism in place. Then we can throw out unconfirmed emails at some point.

Some people complaining on HackerOne is better than making it difficult for a lot of people to sign up to our newsletter.

**Comment by jospoortvliet** [comment]
Ok, so I'd be happy to remove it but... I... don't... know... how! Yes, I looked 😢 

I can configure the captcha in the settings (bottom of page) but there's no obvious 'disable' button or something....

**Comment by LukasReschke** [comment]
> Ok, so I'd be happy to remove it but... I... don't... know... how! Yes, I looked 😢
> I can configure the captcha in the settings (bottom of page) but there's no obvious 'disable' button or something....

Nicht verzagen, @lukasreschke fragen 😉

**Comment by LukasReschke** [comment]
@jospoortvliet I removed the captcha related code.

**Comment by jancborchardt** [comment]
@LukasReschke our new king :crown: 

So we can close this? ;)
