### ISSUE TITLE
Directly integrate the newsletter subscription input field and button to the page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#157]
With phpList you can directly integrate it: https://www.phplist.com/ajaxdemo

No need for a redirect, people can just put in their info directly on the frontpage. Much easier.

**Comment by Espina2** [comment]
@jancborchardt we should see if anyone can implement this. :)

**Comment by jancborchardt** [comment]
Whoops, duplicate of https://github.com/nextcloud/nextcloud.com/issues/53 – let’s continue there ;)
