### ISSUE TITLE
Link underline on the new website

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#158]
Opening as new issue cause I don’t see it as blocking for the release.

- [ ] Instead of using text-decoration:underline, we should use `border-bottom: 1px solid #textcolor;` as it does not cut the descenders of the text and also has a bit more space to the text.
- [ ] In the navigation, the hover should use the big underline effect same as for the currently active element. (Instead of the current small underline which seems strange in comparison.)

**Comment by Espina2** [comment]
@jancborchardt can you post print screens for the first issue you are talking about.

**Comment by jancborchardt** [comment]
Sure, this is from the »Contact us« links on the Enterprise page for example: https://nextcloud.com/enterprise/?staging=true

Current situation with text-decoration:underline;
![capture du 2016-10-05 00-31-05](https://cloud.githubusercontent.com/assets/925062/19094931/3fbd936e-8a93-11e6-9910-1d8f2e81ef1b.png)

Correct with border-bottom: 1px solid #fontcolor; – not cutting through the descenders and leaving some proper space, not so cramped.
![capture du 2016-10-05 00-31-31](https://cloud.githubusercontent.com/assets/925062/19094930/3fbc6cfa-8a93-11e6-8167-3fe1a969b7ea.png)

**Comment by Espina2** [comment]
Oh Thanks. Nice tip.

**Comment by Espina2** [comment]
This is already fixed.
