### ISSUE TITLE
No Changelog for 23.0.0

### ISSUE THREAD

**Issue by Delphinator** [nextcloud/nextcloud.com#1583]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to the [server download page](https://nextcloud.com/install/#instructions-server). "Latest stable version" is 23.0.0.
2. Follow the link to the [changelog](https://nextcloud.com/changelog/). Latest version with a changelog entry is 22.2.3.
3. [Latest release](https://github.com/nextcloud/server/releases/latest) here on GitHub is 23.0.0 (with no description) from eight days ago.

This happened with at least v20.0.0 (see nextcloud/server#23219) and v20.0.8 (see nextcloud/server#25792) as well.

### Expected behaviour
The changelog should be updated before or very shortly after a release is made - especially a new major version. Having no published changelog for the current stable version for over a week is very odd for a project as big as nextcloud. Please consider, that a new major version indicates possible breaking changes admins might want to know about before upgrading and not finding one will likely delay updates and reduce confidence in the project.

### Actual behaviour
I was unable to find a changelog for 22.2.3 to 23.0.0

**Comment by szaimen** [comment]
Done with https://github.com/nextcloud/nextcloud.com/commit/1b6a449b8db432933f96f34f3f02c61e3bbb71c1

**Comment by morremeyer** [comment]
@szaimen As I wrote in the comment above, it just links to the blog post and that doesn't contain a full list of changes. 

As far as I'm concerned, that's not a changelog entry.

To see the actual changes, a full list of changes besides the large improvements that are announced in the blog Post will be needed.

As 23.0.0 is a major release, I expect breaking changes. However, none of the available documentation lists those. 

How can I get a full list of changes?

**Comment by szaimen** [comment]
cc @jospoortvliet on that

**Comment by morremeyer** [comment]
Yes, thank you! It would be great if that could be either put into the changelog directly or in the upgrading guide with a link to the guide from the changelog
