### ISSUE TITLE
"Contact us" webform unforgiving on phone number

### ISSUE THREAD

**Issue by insightfill** [nextcloud/nextcloud.com#160]
The page https://nextcloud.com/contact/ seems to not allow my US phone number, no matter what format I try. Always directs to "We are very sorry, but there were error(s) found with the form you submitted: The phone number you entered does not appear to be valid, did you add a country code like +49?"

My phone number is the US format of "1-630-XXX-XXXX" and no variation of it seems to get through, nor does the prompt really help me.

(BTW: the last phrase should be two sentences. There should be a period between "valid" and "Did".)

**Comment by tflidd** [comment]
Your number must start with either 00 or +:
https://github.com/nextcloud/nextcloud.com/blob/master/page-contactsubmit.php#L32
+1-630-.. should work.

**Comment by MariusBluem** [comment]
As @tflidd said, you must include a country code :) Its explained in the field ... Closing here 😉
+49 000 0000000 or 0049 000 0000000 ... both ways working fine (also with other codes than 49 😜 )
