### ISSUE TITLE
Redirection Error on Downloads page(App Image Linux)

### ISSUE THREAD

**Issue by vinay-keshava** [nextcloud/nextcloud.com#1617]
https://github.com/nextcloud/desktop/releases/download/v3.4.3/Nextcloud-3.4.3-x86_64.AppImage

Redirection Error while downloading the app image of Linux client 
Please Update the link of  Download for Linux .

**Comment by solracsf** [comment]
Seems fixed.

**Comment by vinay-keshava** [comment]
Yes it is fixed
