### ISSUE TITLE
[Bug]: website lists release for 23.0.4 as _tomorrow_

### ISSUE THREAD

**Issue by r2evans** [nextcloud/nextcloud.com#1622]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The website's `/changelog/` lists 23.0.4 as being released _tomorrow_ (and the `.tar.bz2` and `.zip` files are not found).

![image](https://user-images.githubusercontent.com/5815808/159311240-bfec8925-ff32-4da6-a3fc-0912d5203524.png)

For the record, as I type this it is 2022-03-21 16:39 UTC, so while it is true that some countries in the world are currently in 2022-03-22, it is not for what I assume is the NC office:

![image](https://user-images.githubusercontent.com/5815808/159311182-2699cc60-6825-432c-a823-2dc4d03a6895.png)

### Steps to reproduce

1. Visit https://nextcloud.com/changelog/

### Expected behavior

Either not visible yet (since the `.tar.bz` and `.zip` files are 404) or correct the date to `2022-03-21` and make the files available.

Perhaps it should be `23.0.3` instead? While NC has historically skipped some release numbers, I do see that `23.0.3` is found in https://download.nextcloud.com/server/releases/. The release-date is still an issue. (Neither are available on hub.docker.com, a small divergence from previous release trends, so I'm not certain which way this should be going.)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

**Comment by solracsf** [comment]
Cc @jospoortvliet 👀

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/nextcloud.com/commit/dd8c217f6ce3bba81518dc24db8a3a0f50648291
