### ISSUE TITLE
Website lists 24.0.0 as latest server release, while repository says it's v23.0.4

### ISSUE THREAD

**Issue by LukeLR** [nextcloud/nextcloud.com#1643]
On https://nextcloud.com/install/#instructions-server, the latest archive file version is said to be `24.0.0`. However, when checking the releases in the [GitHub repository](https://github.com/nextcloud/server/releases), the latest stable version is `v23.0.4`. Is that expected?

**Comment by tcitworld** [comment]
There is a tag anyway https://github.com/nextcloud/server/releases/tag/v24.0.0

**Comment by LukeLR** [comment]
Thanks, so it's an issue with GitHub not displaying this tag as a release?

**Comment by tcitworld** [comment]
Nope, a release was indeed not created, but that's not an issue. The point is that the code is tagged properly, and the archive file version corresponds to a correct version of the code.

**Comment by LukeLR** [comment]
So the GitHub releases displaying stable releases is only optional?

**Comment by tcitworld** [comment]
Absolutely

**Comment by LukeLR** [comment]
Okay, thanks for clarification! I'll close this issue in this case. Have a nice day, and keep up the great work with Nextcloud! :)
