### ISSUE TITLE
Blog about the new website design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#165]
Now that the design is deployed and we also have the [blog post of the conference workshop](https://nextcloud.com/blog/nextcloud-design-team-updates/) up ([retweet it](https://twitter.com/jancborchardt/status/784017328648388608) by the way! ;) – we should really blog about it!

@Espina2 it would be a great opportunity to describe the workflow of doing it, what motivated you to do it, the design reasoning behind it etc. :)

cc @nextcloud/designers for info, and since all of you are very welcome to blog about the field you are working on, as discussed. :rocket:

**Comment by Espina2** [comment]
@jancborchardt thanks for the invition I have to think about it, but for sure.

**Comment by Espina2** [comment]
@jancborchardt 
This is Still up?

**Comment by MorrisJobke** [comment]
> @jancborchardt
> This is Still up?

Sure :) better late than never :)

**Comment by Espina2** [comment]
I will write something. :)

**Comment by mathiasconradt** [comment]
@MorrisJobke @jancborchardt I guess this ticket can be closed, since it's already more than a year old and not relevant anymore.

**Comment by MariusBluem** [comment]
> @MorrisJobke @jancborchardt I guess this ticket can be closed, since it's already more than a year old and not relevant anymore.

Yes.
