### ISSUE TITLE
"select your country" dropdown on box purchase page not working

### ISSUE THREAD

**Issue by tomfotherby** [nextcloud/nextcloud.com#172]
On the webpage to buy a nextcloud box ( https://nextcloud.com/box/ ) - the "select your country" dropdown doesn't do anything. I tried Firefox and Chrome. I think this bug means it's not possible to purchase a box?  (or I'm being stupid, a very real possibility :stuck_out_tongue_winking_eye: ).

I wanted to let the nextcloud box team know about this, not sure if this is the right place.

**Comment by Espina2** [comment]
Yes you are in the right place. :) I already commit a fix for that. Some javascript files from bootstrap are loaded in the page.
