### ISSUE TITLE
Nextcloud logo is in a bad quality

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#173]
Since the redesign of the page (...which is very nice 💪) the Nextcloud logo in the top-right corner of the page seems to be in a bad quality. White on blue seems to be good, but the blue/black on white is a bit strange.

Safari 10.0 on macOS Sierra

@Espina2 @jospoortvliet

**Comment by Espina2** [comment]
I think is already fixed but not merged. 

https://github.com/nextcloud/nextcloud.com/pull/168#issuecomment-252607762

**Comment by LukasReschke** [comment]
Deployed
