### ISSUE TITLE
Front Page Latest news Improvement

### ISSUE THREAD

**Issue by Espina2** [nextcloud/nextcloud.com#176]
I think the area with the latest news in front page are a bit boring. For that I start create this illustration (not finish yet). What you think about it? Should I invest more time in it or not?

![frequently asking questions](https://cloud.githubusercontent.com/assets/11150206/19279691/57a0a74a-8fda-11e6-82ac-18e8d78727bd.png)

@nextcloud/designers @LukasReschke @jospoortvliet

**Comment by MorrisJobke** [comment]
I like it 👍

**Comment by skjnldsv** [comment]
Nice! 👍

**Comment by jancborchardt** [comment]
Looks good! Let’s also add the avatars to the sections because without images and only text there it looks quite sad ;)

**Comment by jospoortvliet** [comment]
I'd love to add avatars but no clue how, sorry.
