### ISSUE TITLE
More padding for navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#178]
Currently the clickable area of the top navigation is very small, basically just the text. The padding of the entries should make the element at least 44*44px big. And ideally extend to the top of the viewport and the bottom of the navigation to provide the most easy to click area.

cc @nextcloud/website

**Comment by Espina2** [comment]
It will be fixed automatically in this PR https://github.com/nextcloud/nextcloud.com/pull/227
