### ISSUE TITLE
Remove sharepoint from feature list

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#180]
https://nextcloud.com/features/
lists sharepoint under the supported external storage type. However, it is not documented anywhere and there are plans to integrate it in NC 11: https://github.com/nextcloud/server/issues/745

Perhaps we should remove it from the list until it is fully supported, there already were some people asking for it: https://help.nextcloud.com/t/integrate-sharepoint-libraries/3442

**Comment by MariusBluem** [comment]
Thank you for the report 💪
