### ISSUE TITLE
Install page broken

### ISSUE THREAD

**Issue by Skywalker-11** [nextcloud/nextcloud.com#190]
The page https://nextcloud.com/install/#install-clients is broken: 
![screenshot](https://cloud.githubusercontent.com/assets/11180862/19429816/f935de06-9451-11e6-80a1-6044eb5eb8d6.jpg)

Tested with current Firefox and Google Chrome.

Chrome shows the following error in the console:
cd699.js?x16328:9 Uncaught TypeError: $(...).velocity is not a function(anonymous function) @ cd699.js?x16328:9o @ cd699.js?x16328:1fireWith @ cd699.js?x16328:1ready @ cd699.js?x16328:1B @ cd699.js?x16328:1

**Comment by Skywalker-11** [comment]
is fixed

**Comment by jospoortvliet** [comment]
I still appreciate the report!
