### ISSUE TITLE
Should the download button in the header be white?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud.com#194]
![nextcloud_-_2016-10-17_13 48 53](https://cloud.githubusercontent.com/assets/213943/19436450/777fbad4-9470-11e6-867b-84f699921642.png)

I think it should be white to have a bigger contrast to the other links

**Comment by Espina2** [comment]
Im working in a newer solution with dropdowns for more easy navigation. We discuss that on that conference. 

You can take a look what Im talking about here: https://scene.zeplin.io/project/57bf54c24ff046f70c9b9694/screen/57c9aa04d553cb03101e7ab5

**Comment by jancborchardt** [comment]
@Espina2 »Download« should remain styled like a button though to be a clear call to action, right?

**Comment by jospoortvliet** [comment]
Agreed with Jan, the download should stay that way. We could make the background white, too, text blue or dark gray but I like the current look. I do notice that the white outline is much smaller than it used to be, it was a few pixels wide, now it is very thin.

**Comment by Espina2** [comment]
If you guys say that download should be a call to action, yes they should have that style.
