### ISSUE TITLE
Replace image of 30-something white bearded computer dude with something nicer

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#197]
The Nextcloud community is diverse, as are the users. This should reflect on our frontpage. We could even have different pictures and show one at random. But only having one white male is a bit meh.

cc @jospoortvliet @Espina2 where did you get the photo from? Can we get other more diverse photos too?

**Comment by Espina2** [comment]
@jancborchardt 

He should look for a nice image for sure. But for now it talks about Nextcloud being perfect for Home and Office, and the image good or bad show that. At the time its the best free image that I see that help visualize the copy. 

@jospoortvliet already told me that right now the frontpage looks very home user and we need to make a better connection with enterprise to. :)

Anyway if can help or suggest better photos it would be nice. :)

**Comment by jancborchardt** [comment]
What do you think about this (would simply need to be mirrored to work in our current layout):
![startup-photos-largesf](https://cloud.githubusercontent.com/assets/925062/19444772/21acb2de-9492-11e6-9a72-e83d5b7ad03f.jpg)
https://www.pexels.com/photo/working-woman-technology-computer-7374/

or this:
![startup-photos-larges](https://cloud.githubusercontent.com/assets/925062/19444770/21a6fdc6-9492-11e6-8299-90cfc76f397b.jpg)
https://www.pexels.com/photo/working-woman-person-technology-7375/

or this (also mirrored, and with Apple advertising removed ;D)
![startup-photos-large](https://cloud.githubusercontent.com/assets/925062/19444771/21a79d94-9492-11e6-935f-0b0de5448d7d.jpg)
https://www.pexels.com/photo/macbook-apple-woman-computer-7362/


They also all have more of a work-vibe to it. And all are CC0 and available in high res.

**Comment by Espina2** [comment]
I will test it as soon as I can, and I will post here how it looks. Thanks :)

**Comment by oparoz** [comment]
The first one works well, the 2nd one shows geek content and the 3rd one is too consumer oriented.
Looking forward to seeing more examples :)

**Comment by jancborchardt** [comment]
@oparoz that’s what I thought too, the first one works best.
