### ISSUE TITLE
Box Layout

### ISSUE THREAD

**Issue by Espina2** [nextcloud/nextcloud.com#215]
So I almost finish to design the box layout page but I need to get some opinions and ideias from you guys. Still need to design icons for list inside the Technology.

@nextcloud/designers @jospoortvliet 

![box](https://cloud.githubusercontent.com/assets/11150206/19593149/07794660-9777-11e6-92ce-c6039f92f277.jpg)

**Comment by jancborchardt** [comment]
Looking good! What’s that blue circle right next to the »Bring your data home« heading?

Apart from that just some wording stuff I guess @jospoortvliet wants to take a look at. :)

Maybe a more fitting slogan would be: »A safe home for all your data. In your home.« to play on our main slogan.

**Comment by Espina2** [comment]
The little dot is from the logo and I have it in the others page's to. Its only a graphical element, but It can be remove.

**Comment by Espina2** [comment]
I need copy for the text after How to box. But I think all in here is not hard to do in code, I have this in mind when design.

**Comment by MorrisJobke** [comment]
Awesome 🙌 I like it ❤️

**Comment by jancborchardt** [comment]
> The little dot is from the logo and I have it in the others page's to. Its only a graphical element, but It can be remove. 

Yeah, that would be cool. It looks a bit strange, as if it’s clickable or serves a purpose.

> I need copy for the text after How to box.

»The Nextcloud Box is very easy to assemble. It comes with all necessary screws and a screwdriver. The lid uses magnets (magic!) so you can quickly open and close it.« :)

**Comment by Espina2** [comment]
Done it
