### ISSUE TITLE
Naming files broke git

### ISSUE THREAD

**Issue by Espina2** [nextcloud/nextcloud.com#226]
Please dont give the same name only changing the uppercase to different files since it broken git on mac and windows systems.

![screen shot 2016-10-22 at 23 09 32](https://cloud.githubusercontent.com/assets/11150206/19622874/a29879d2-98ac-11e6-83bf-6f287c9112d8.png)

This article below shows why it happens. 

http://blog.endpoint.com/2016/01/file-names-same-except-for.html

![image](https://cloud.githubusercontent.com/assets/11150206/19622893/2d38ea18-98ad-11e6-9806-09b14422236b.png)

![screen shot 2016-10-22 at 23 11 03](https://cloud.githubusercontent.com/assets/11150206/19622881/d489f4ac-98ac-11e6-81fe-d54d743a6e77.png)

@jospoortvliet When you can please fix this. I think that anyone who use MAC or Windows it will be stuck until you rename and do a git pull.

**Comment by Espina2** [comment]
@telmaantunes fixed here https://github.com/nextcloud/nextcloud.com/pull/228 using my account, and merged.

**Comment by jospoortvliet** [comment]
Ah, I'll try to avoid this, but in general - use a proper operating system or filesystem, sjees ;-)

**Comment by telmaantunes** [comment]
Or a proper naming convention... :) 2 files with the same name (only changing the camel case) it's never a good idea. A good convention for images is to use some-example.png

**Comment by jospoortvliet** [comment]
@telmaantunes tsss, it is far easier for me to demand that the world adjusts to me than the other way around. ;-)

but yes, you're right, I have to be more disciplined. @Espina2 is teaching me!
