### ISSUE TITLE
link to design page on the Get Involved (contribute) page is broken

### ISSUE THREAD

**Issue by adsworth** [nextcloud/nextcloud.com#232]
Hi,
the link to the design page is broken.

https://github.com/nextcloud/nextcloud.com/blob/master/page-contribute.php#L52

No idea how to fix it, since I can't actually find the correct URL for the design page, otherwise this would have been be a PR.

**Comment by jospoortvliet** [comment]
Ah, my mistake, thanks for spotting: the page exists, I even recently updated it, it just wasn't published. Good now, see https://nextcloud.com/design
