### ISSUE TITLE
PHP-code as clear text on feature page 

### ISSUE THREAD

**Issue by Crizz0** [nextcloud/nextcloud.com#245]
URL: https://nextcloud.com/features/ 

There is a lost `');?>` on the feature page, directly under the list for "The Calendar and Contacts app feature:".

![nextcloud-features](https://cloud.githubusercontent.com/assets/1311778/19814761/fc7b7430-9d3f-11e6-8a9b-567ecfc576eb.PNG)

**Comment by Espina2** [comment]
Thanks @Crizz0. I fixed here https://github.com/nextcloud/nextcloud.com/pull/246
