### ISSUE TITLE
Broken Blog Images

### ISSUE THREAD

**Issue by raghunayyar** [nextcloud/nextcloud.com#251]
The blog is broken as of now, the images needs a max-width I think for a quick fix.

@nextcloud/designers @jospoortvliet 

<img width="1246" alt="screen shot 2016-11-01 at 1 47 54 pm" src="https://cloud.githubusercontent.com/assets/992488/19890264/d13297fc-a039-11e6-889f-7f8cfd7f307c.png">

**Comment by jancborchardt** [comment]
@raghunayyar can you open a pull request to fix it? :)

**Comment by jospoortvliet** [comment]
Should be fixed now, if not - pls let me know if you see it again.
