### ISSUE TITLE
Links get grey on some pages

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#253]
![img_0236](https://cloud.githubusercontent.com/assets/19711361/20031887/5f8e83a6-a37f-11e6-8bbe-bc1f05177ee6.PNG)

Only on old pages when you scroll down (not on "Enterprise" and "Home") ... Tested with Safari ;) 

@Espina2 @jospoortvliet

**Comment by Espina2** [comment]
@MariusBluem 
This is weird, because javascript block the scroll. Did you use the the scroll bar or the mouse? 

Anyway this will be fixed when the new Header are finished.

**Comment by jospoortvliet** [comment]
new header in, should be fixed!
