### ISSUE TITLE
Download links missing

### ISSUE THREAD

**Issue by benediktg** [nextcloud/nextcloud.com#254]
I think that there are missing links to the Nextcloud releases on this page: https://nextcloud.com/changelog/

![screenshot_20161106_215628](https://cloud.githubusercontent.com/assets/14795615/20041586/ee6f5e0a-a46b-11e6-87db-6e9fecdd8846.png)

Around the 9.0.54 there should be some in place…

**Comment by MariusBluem** [comment]
You are right ... Before we've fixed this, https://download.nextcloud.com/server/releases/ is the place you should look for other releases as the current 😅 Thank you for reporting 👊 

@jospoortvliet

**Comment by jospoortvliet** [comment]
@LukasReschke is that page generated by some scripty thing or manually? If manually, I can fix this, if scripty scripty we should fix the script!

**Comment by LukasReschke** [comment]
> @LukasReschke is that page generated by some scripty thing or manually? If manually, I can fix this, if scripty scripty we should fix the script!

Manually ;)

**Comment by MariusBluem** [comment]
They are there now -> Closing 😉
