### ISSUE TITLE
Error 404 when acessing Admin documentation from the install page

### ISSUE THREAD

**Issue by krisman** [nextcloud/nextcloud.com#255]
When I go to https://nextcloud.com/install/ and click the "Admins" link under the "Read the documentation" section, I get a Page Not Found error.  The browser URL box shows:

https://nextcloud.com/install/<?php echo $DOCUMENTATION_ADMIN; ?>

Which looks to me like it failed to identify the above as a valid php code?  I don't do php, so I'm clueless.  

I've got Firefox 47.0.1 here, with noScript 2.9.0.14, but I made sure to disable it and got the same result.

**Comment by krisman** [comment]
Oh, if I go to that page footer and click the 'Admin Manual' link under the 'Resources' section, it gets me to:
https://docs.nextcloud.com/server/10/admin_manual/

Which works great for me and has the information I was looking for.

**Comment by MariusBluem** [comment]
All documentation links are not working 🙈 Thank you for reporting 😅

**Comment by jospoortvliet** [comment]
They work now :+1:
