### ISSUE TITLE
Strong directory permission script mismatches instructions

### ISSUE THREAD

**Issue by strk** [nextcloud/nextcloud.com#259]
This page:
https://docs.nextcloud.com/server/10/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions

it says to make webserver user own `config/` `data/` and `apps/` but then the script also grant ownership of `assets` and `themes`  and `updater` (and the assets/ directory doesn't even exist)

Which of the two is correct and which is wrong ?

**Comment by jospoortvliet** [comment]
That I don't know, @LukasReschke does for sure.

But it's a documentation issue in any case, would you care to open this in the docu repo: https://github.com/nextcloud/documentation

Thanks!
