### ISSUE TITLE
Consider about making the Download button in Header a bit smaller

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#267]
I think this button is a bit oversized and its edges are too near at the Demo button 😁 What do you guys think? @nextcloud/designers 

<img width="253" alt="dl_button" src="https://cloud.githubusercontent.com/assets/19711361/20228701/d3fbbc9a-a852-11e6-9f34-b7b8b12ff572.png">

cc @Espina2 @jospoortvliet

**Comment by Espina2** [comment]
This Header is going to be replaced by a new home.

https://github.com/nextcloud/nextcloud.com/pull/227

Also I'm checking all the buttons since I made them all a bit oversized, so it will be fixed in another PR.

**Comment by MariusBluem** [comment]
Didn't know that this is already fixed with that 😅 THX!!!
