### ISSUE TITLE
Wrong favicon shown

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#282]
Where is this favicon with text loaded from?
![capture du 2016-12-01 09-35-59](https://cloud.githubusercontent.com/assets/925062/20786985/d1eff23e-b7a9-11e6-9b79-349eb4fe849c.png)
Makes little sense since the text isn’t legible and just makes the logo look non-centered and smaller.

It’s strange since https://github.com/nextcloud/nextcloud.com/tree/master/assets/img/common has the correct favicon.png and favicon-touch.png

Any idea @nextcloud/website? Do you also see this wrong favicon? I have it showing here with Firefox.

**Comment by Espina2** [comment]
This not make any sense at all. Do you have the same bug on master?

**Comment by LukasReschke** [comment]
Well:

> <link rel="icon" href="https://nextcloud.com/media/logo-nextcloud-300x300.png?x16328" sizes="192x192" />

**Comment by Espina2** [comment]
If you look for the files in the master you see this fav.icon doesn't exist. I think problem come for an optimization to the images make a month or two ago. 

![screenshot_20161201_110339](https://cloud.githubusercontent.com/assets/11150206/20791639/e426d740-b7b5-11e6-8d24-623fdc08a218.png)

**Comment by jancborchardt** [comment]
It’s on the actual website https://nextcloud.com – same in Chrome:

![capture du 2016-12-02 13-57-37](https://cloud.githubusercontent.com/assets/925062/20834790/5ade2e6a-b897-11e6-93e9-ec9116db9f73.png)
(Left the website, right the docs, different subdomain)

**Comment by jospoortvliet** [comment]
Ha! Turns out, the favicon is set in wordpress. All those icons I've put EVERYWHERE in our Nextcloud site - none do anything ;-)

I've fixed it. All good now!

**Comment by jancborchardt** [comment]
@jospoortvliet thanks :D
