### ISSUE TITLE
Jobs page - can't expand job entries on Safari (on iOS)

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/nextcloud.com#293]
* opening the jobs page
* try to open the job openings by clicking the header
* the description is not shown - noting happens

@Espina2 @LukasReschke Could you reproduce this?

cc @jospoortvliet

**Comment by LukasReschke** [comment]
Broken here as well.

**Comment by MorrisJobke** [comment]
Weirdly it works in the emulator inside Safari on macOS -.- (so no easy debugging)

**Comment by Espina2** [comment]
They show but not open? @MorrisJobke

**Comment by MorrisJobke** [comment]
> They show but not open? @MorrisJobke @LukasReschke

Correct :/

**Comment by Espina2** [comment]
What handle this are bootstrap. Did you tried before the new Header? Did you already made a hard refresh here to?

**Comment by MorrisJobke** [comment]
> What handle this are bootstrap. Did you tried before the new Header? Did you already made a hard refresh here to?

I have no idea how to do a hard refresh on iOS 🙈

**Comment by Espina2** [comment]
Private mode should make the work here. @MorrisJobke

**Comment by Espina2** [comment]
@MorrisJobke you already make the test in private mode?

**Comment by MorrisJobke** [comment]
> @MorrisJobke you already make the test in private mode?

Yes - same result - the text doesn't show up/doesn't expands

**Comment by MorrisJobke** [comment]
> Yes - same result - the text doesn't show up/doesn't expands

I just retested again and still no change.

**Comment by jospoortvliet** [comment]
sigh, we use standard bootstrap here, nothing special. I see no javascript errors in the console, all is good :sob:

**Comment by Espina2** [comment]
I discover the bug, so I don't know why but here we instead of using the href id for toggle the content we are using the data attribute. So the problem is the bootstrap like I said. 

You can see were that the first one works (the one I changed) and the others no.

https://cloud.paulomoura.com.pt/owncloud/index.php/s/NsDVufCzHzbX5UI

I will make a pull request to this and ask Jos to deploy, so you guys can test.

**Comment by Espina2** [comment]
This should be fix here. https://github.com/nextcloud/nextcloud.com/pull/303

**Comment by MorrisJobke** [comment]
Tested and works 👍
