### ISSUE TITLE
Dead link on Bugtracker pager

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/nextcloud.com#295]
There is a dead link on the [Bugtracker](https://docs.nextcloud.com/server/10/developer_manual/bugtracker/index.html) page.

The link to the **Client Repository** (https://github.com/nextcloud/client/issues) is not working.

**Comment by jospoortvliet** [comment]
This is a documentation issue - would you be so kind to file it in https://github.com/nextcloud/documentation/issues ?
