### ISSUE TITLE
SASS (?) Error on /privacy

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/nextcloud.com#298]
![tmp_22787-screenshot_20161207-161148-1341344727](https://cloud.githubusercontent.com/assets/4741199/20973227/2647c49a-bc98-11e6-994b-426531ff7929.png)

CC @nextcloud/designers

**Comment by jancborchardt** [comment]
cc @Espina2 can you check this out?

**Comment by Espina2** [comment]
I don't have this error. @stefan-niedermann can you do a hard refresh and try again please?

**Comment by stefan-niedermann** [comment]
Fixed with hard refresh.

**Comment by Espina2** [comment]
Nice, thanks for the report. :+1:
