### ISSUE TITLE
.intro-text is a bit drifted to the left

### ISSUE THREAD

**Issue by tchncs** [nextcloud/nextcloud.com#3]
![2016-06-05-111128_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/15804590/7a2c29dc-2b0e-11e6-92a8-2e4a2fd4c648.png)

**Comment by mar1u5** [comment]
Thank you for reporting. I've looked at it, and i can reproduce this with Safari aswel 😉 
Can you look into the code and create a pull request? @tchncs

**Comment by mar1u5** [comment]
cc @nextcloud/designers

**Comment by tchncs** [comment]
@mar1u5 i agree, this is not a 'big' thing to fix. 
I am very busy this hours so i cannot do this but i wanted to report this anyway because i think this homepage has a very high priority, also to advertise nextcloud.
So i just reported because it would need several hours until i am able to look at this.
Hope you understand ;)

**Comment by mar1u5** [comment]
No problem 😉I just wanted to say is that you are always welcome to report bugs and contribute 😅 You are welcome at our IRC `#nextcloud` and in our forum https://help.nextcloud.com.

**Comment by mikebabb** [comment]
Closing this issue as [pull request 4](https://github.com/nextcloud/nextcloud.com/pull/4) resolved it. Thanks for reporting, @tchncs!

**Comment by jancborchardt** [comment]
:rocket: you folks rock!
