### ISSUE TITLE
Background doesn't fit to window if it's too narrow

### ISSUE THREAD

**Issue by sandydo** [nextcloud/nextcloud.com#300]
When opening the home page of nextcloud.com on a smartphone there is some white space on the right border. The background doesn't fit to the window. The only thing which fits in the window is the "subscribe to newsletter" button.

The same happens when narrowing the browser window!

![screenshot_2016-12-08-10-19-33](https://cloud.githubusercontent.com/assets/5897058/21019243/033e8910-bd70-11e6-885c-47be63b095d3.png)
![screenshot_2016-12-08-10-19-55](https://cloud.githubusercontent.com/assets/5897058/21019245/0403f5ce-bd70-11e6-8497-d2e1f41203ac.png)

**Comment by jospoortvliet** [comment]
Yeah, it is the newsletter button, it is too wide. Let me see if I can fix it, thanks!

**Comment by jospoortvliet** [comment]
fixed, deployed. Thanks!
