### ISSUE TITLE
Consider about webrtc page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#311]
**Features > Video chat** is currently promoting Spreed.ME, the docker-image and the Spreedbox.
We should think about that, since we have our cool new Spreed now ... 😉 Currently, this is very confusing for the most people 😁 

https://nextcloud.com/webrtc/

@jospoortvliet @nickvergessen @Ivansss

**Comment by jospoortvliet** [comment]
yeah, this needs to be rewritten. I'd like to keep the current page somewhere, or at least the manual/how-to, but this page should be about the new app I suppose. Also a call for @karlitschek  - is the new spreed 'ready' to be the standard? If so, the blog by @Ivansss can be used as a base - https://nextcloud.com/?p=1399

**Comment by karlitschek** [comment]
We should switch over to the new Nc11 Spreed app. It is good enough for most users

**Comment by jospoortvliet** [comment]
Ok, I've put this on my (long) todo list...

**Comment by jospoortvliet** [comment]
@MariusBluem have had any time for this page?

**Comment by MariusBluem** [comment]
I am on it 😁

**Comment by MariusBluem** [comment]
Done.
