### ISSUE TITLE
Fix Glitches

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#314]
The new header (which is awesome 🙌) introduced some gliches appearing on pages without redesign:

- Example: Scroll up if you are already on the top of a page

- Download page:
![bildschirmfoto 2016-12-15 um 10 46 19](https://cloud.githubusercontent.com/assets/19711361/21219164/e4fb689e-c2b3-11e6-9f0f-f135ad35beae.png)

@Espina2 @jospoortvliet

**Comment by Espina2** [comment]
Please add the pages you with glitches here. I will close this issue for more easy tracking.

https://github.com/nextcloud/nextcloud.com/issues/297
