### ISSUE TITLE
Replace "Follow us"-Footer with icons

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#317]
In the footer we are linking to Google+, Facebook, Twitter and RSS. We should use Icons instead of text there 😉 

@Espina2 @jospoortvliet

**Comment by Espina2** [comment]
Why?

**Comment by Espina2** [comment]
@MariusBluem 
Can I close this one?

**Comment by MariusBluem** [comment]
Let's do ... the links are enough 😁
