### ISSUE TITLE
Different footers on homepage and other pages

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#318]
The footers on the pages are different. On the homepage, it looks like this:

![bildschirmfoto 2016-12-16 um 09 45 26](https://cloud.githubusercontent.com/assets/19711361/21256763/7fd3d822-c374-11e6-99aa-8dffdb1d2424.png)

...on all other pages it looks like I think it should 😁:

![bildschirmfoto 2016-12-16 um 09 45 30](https://cloud.githubusercontent.com/assets/19711361/21256783/98f1c896-c374-11e6-9cd2-8303accb435a.png)

What do you think? @jospoortvliet @Espina2

**Comment by jospoortvliet** [comment]
yeah, it's probably a bug in the CSS that makes it look different on the home page. If you can track it down, that would be awesome :D

**Comment by MariusBluem** [comment]
also happening on all other "new" pages: e.g. https://nextcloud.com/secure/

**Comment by Espina2** [comment]
I see it everywhere! Where you see the correct version?

**Comment by MariusBluem** [comment]
https://nextcloud.com/install/ 😁 @Espina2

**Comment by Espina2** [comment]
We already fix that. :)

**Comment by MariusBluem** [comment]
Fixed 👍
