### ISSUE TITLE
fix 'nextcloud 10' mentions on home page and footer

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#327]
The footer still links to Nc10. Should be updated using the variable for that, like used on pages like our install page.

The front page has a feature overview with Nc10 features - should be updated to 11 with info and screenshots from announcement.

**Comment by MariusBluem** [comment]
> The footer still links to Nc10. Should be updated using the variable for that, like used on pages like our install page.

#329 fixes this for now - without variables - with Nextcloud 12 we should do this either 😉 

> The front page has a feature overview with Nc10 features - should be updated to 11 with info and screenshots from announcement.

This does not work - or am I wrong. So nobody can see it 😅 @jospoortvliet
