### ISSUE TITLE
Important call to actions of Enterprise & Pricing page not reachable on mobile

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#345]
This whole bar on the Enterprise & Pricing pages:
![capture du 2017-01-17 13-30-03](https://cloud.githubusercontent.com/assets/925062/22020661/b7c2a6ce-dcb9-11e6-9613-8173c02eb55b.png)

Is not there on mobile at all. Can we place it like it is on the desktop, having it sticky at the top? cc @nextcloud/website

**Comment by Espina2** [comment]
What you suggest? With all the information it have here it doesn't work on mobile.

**Comment by jancborchardt** [comment]
The left part is only the points which are listed below anyway, so it’s not that important on mobile. But the calls to action could be placed nicely between the header image and the first points, like so:
![capture du 2017-01-17 15-21-12](https://cloud.githubusercontent.com/assets/925062/22024114/2c1fdc80-dcc9-11e6-8af6-dea001c6e111.png)
What do you think?

**Comment by Espina2** [comment]
I think its more natural instead of having a double bar on top, push this to bottom and make it fix. I think its better. Anyway I will try.

**Comment by jancborchardt** [comment]
@Espina2 yeah, that seems useful to get people into the funnel. How about we also style the »Pricing« (let’s cut the text) button as white, so the »Get a quote« button is the primary action?

**Comment by Espina2** [comment]
Yup but we are going to switch the table of the Pricing page, and we can think on that we work on that.

**Comment by Espina2** [comment]
@jancborchardt 
I made the buttons to show in mobile. You can take a look at the live version.
