### ISSUE TITLE
Capitalization of call-to-action bar on Pricing & Enterprise pages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#346]
This whole bar uses all-caps:
![capture du 2017-01-17 13-30-03](https://cloud.githubusercontent.com/assets/925062/22020682/dfb6cb92-dcb9-11e6-8548-23e2f9457353.png)

As talked about before, we never ever do that. It looks ugly, is not very legible, you can’t discern where one entry on the left ends and the other one begins, and it seems as if we are screaming at people.

We always only capitalize the first character of an entry or a button. cc @nextcloud/website

**Comment by Espina2** [comment]
Fixed here https://github.com/nextcloud/nextcloud.com/pull/352

**Comment by jancborchardt** [comment]
@Espina2 if you mention `fix #issuenumber` in the pull request, the issue will automatically be closed once the pull request is merged :) Cause we only close issues once the fix has actually been merged.

**Comment by Espina2** [comment]
I didn't know that. Thanks. ;)
