### ISSUE TITLE
Fade on top of website?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#347]
I just noticed this on the top of the website:
![capture du 2017-01-17 13-31-42](https://cloud.githubusercontent.com/assets/925062/22020747/365ef334-dcba-11e6-96b5-f22baca2d754.png)

It looks very strange, especially since everything else is plain color. What was the reason for adding this? cc @nextcloud/designers

**Comment by MariusBluem** [comment]
Which browser are you using 😁 @jancborchardt

**Comment by skjnldsv** [comment]
netscape@windowsNT! 😆

**Comment by jancborchardt** [comment]
Happens both in Chrome and Firefox on Ubuntu. Likely with the last deploy, so clear your cache or test with an incognito window. ;)

**Comment by MariusBluem** [comment]
Ah... Call me stupid ... But isn't this more a feature than a bug 😜😅

**Comment by Espina2** [comment]
Its a missplaced code. I will fix that in a minute.

**Comment by Espina2** [comment]
Fixed Here
https://github.com/nextcloud/nextcloud.com/pull/352
