### ISSUE TITLE
css.orig files?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#350]
Are these files like custom.css.orig and custom.scss.orig still needed, or just leftovers? They even have merge conflict traces in them, like:
```
<<<<<<< HEAD
=======

>>>>>>> 73267d428852c47c6c5a900f2041783cabe1eb01
```

Seems like we should delete them? @nextcloud/website

**Comment by Espina2** [comment]
it should be erased

**Comment by Espina2** [comment]
Fixed here https://github.com/nextcloud/nextcloud.com/pull/352
