### ISSUE TITLE
Header of enterprise and pricing is white

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/nextcloud.com#357]
For me (even after a hard refresh) the header of pricing and enterprise is white:

![bildschirmfoto 2017-01-17 um 08 52 57](https://cloud.githubusercontent.com/assets/245432/22025381/fa54c610-dc92-11e6-8429-d20f074560a4.png)

cc @jospoortvliet @Espina2 @LukasReschke

**Comment by Espina2** [comment]
do a print screen of dev tool

**Comment by Espina2** [comment]
ITs fixed here to https://github.com/nextcloud/nextcloud.com/pull/359

**Comment by MorrisJobke** [comment]
It's fixed now 👍
