### ISSUE TITLE
Unstyled elements on pricing page

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/nextcloud.com#358]
Some elements on the pricing page seem to be unstyled (even after a hard refresh):

![bildschirmfoto 2017-01-17 um 08 56 55](https://cloud.githubusercontent.com/assets/245432/22025404/13f28e90-dc93-11e6-88a2-6564ef485882.png)
![bildschirmfoto 2017-01-17 um 08 56 57](https://cloud.githubusercontent.com/assets/245432/22025405/13f58f96-dc93-11e6-832f-68afd99cd74b.png)

cc @jospoortvliet @Espina2 @LukasReschke

**Comment by Espina2** [comment]
I know what it is.
