### ISSUE TITLE
Providers page broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#366]
`headroom is not defined`:
![capture du 2017-01-19 00-19-42](https://cloud.githubusercontent.com/assets/925062/22087219/0a34f6cc-dddd-11e6-8739-7213522cd7c0.png)

cc @nextcloud/website

**Comment by Espina2** [comment]
It will be fixed in the next deploy. It happens in the all older pages.

@jospoortvliet

**Comment by jancborchardt** [comment]
Can you please deploy then @jospoortvliet?

**Comment by jospoortvliet** [comment]
I did but sadly this isn't yet fixed. @Espina2 is working on it...

**Comment by MariusBluem** [comment]
Seems to be fixed 😉
