### ISSUE TITLE
Demo small captcha bug

### ISSUE THREAD

**Issue by claell** [nextcloud/nextcloud.com#368]
When accessing https://demo.nextcloud.com/ I just managed to press "Create Container" before the captcha has loaded. Then an infinite loop of "Status: Giving MySQL a kick . . . . . " etc. is started and nothing happens.

Normally when loading the site completely the button is deactivated until the captcha is solved. Unfortunately there seems to be a short time frame when loading the page where the button can be pressed ignoring the captcha.

**Comment by MariusBluem** [comment]
I had this issue too, some time ago 😅🙈
 
...should we move https://github.com/LukasReschke/nextcloud-demo-docker to `nextcloud` to have a seperate issue tracker for the demo? 🤔 @LukasReschke

**Comment by MariusBluem** [comment]
We have a new demo which should fix such bugs 😜
