### ISSUE TITLE
Android APK on Site

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/nextcloud.com#38]
As requested here:
https://help.nextcloud.com/t/about-downloading-apk-file-of-android-app-from-site/668
We can provide an APK file.
Where and how should we do this?

**Comment by mar1u5** [comment]
I will do this tomorrow :wink:

**Comment by LukasReschke** [comment]
I'm not really a big fan of this, is there any advantage here of not doing this via f-droid which also offers the APK?

Directly using the APK leads to the problem that people will never update, resulting in potential security issues as well as bugs etc…

**Comment by vincchan** [comment]
@LukasReschke As far as I know, installing from apk does not prevent the app being updated from the Play Store. Even the update "notification" will be there. So in this case it wouldn't matter if the user installs it from f-droid/apkmirror.

Don't quote me on that, but I think it uses the package name to link it to the Play Store entry.

**Comment by vincchan** [comment]
@LukasReschke You can test this by downloading for example an outdated version of an app on [APKMirror](http://www.apkmirror.com/) . Play Store will inevitably offer you an update for the app.

**Comment by tobiasKaminsky** [comment]
>I'm not really a big fan of this, is there any advantage here of not doing this via f-droid which also offers the APK?

@LukasReschke see this discussion: https://help.nextcloud.com/t/about-downloading-apk-file-of-android-app-from-site/668

**Comment by jospoortvliet** [comment]
So, as I said in that conversation, too, I'm good with this but we have to find a process to handle website updates and uploading the APK itself somewhere.

**Comment by mar1u5** [comment]
APKs (Beta at least) are stored on Nextcloud's Download Server :wink:

**Comment by tobiasKaminsky** [comment]
> APKs (Beta at least) are stored on Nextcloud's Download Server :wink:

Huh? They are at https://github.com/nextcloud/android/tree/beta/apks and beta is providing an update check for them. @LukasReschke maybe this is something you want to have too for the APKs that are not in play-store nor in f-droid?
