### ISSUE TITLE
No logo visible with current Firefox ESR

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud.com#386]
The logo of the Nextcloud website is not visible using the current Firefox ESR 45.7.0. This happens because Firefox only knows about ```background-position-x``` since version 49.0, see https://developer.mozilla.org/de/docs/Web/CSS/background-position-x.

Fix would be to replace
```
background-position-x: xx;
```
with
```
background-position: xx xx;
```

Firefox ESR will not support this property until March or April, so it would be nice to fix this.
https://www.mozilla.org/en-US/firefox/organizations/faq/

@jancborchardt @Espina2

**Comment by Espina2** [comment]
@raimund-schluessler 
This is still not visible?

**Comment by raimund-schluessler** [comment]
No, it is not visible, see attached screenshot.

<img width="1280" alt="nextcloudwebsitescreenshot" src="https://cloud.githubusercontent.com/assets/2496460/22775530/67737c66-eeac-11e6-8f0e-31798069f92e.png">

The reason is that Firefox ESR 45.7.0. does not support the property ```background-position-x```.

**Comment by jancborchardt** [comment]
@raimund-schluessler do you want to submit a pull request? :)

**Comment by Espina2** [comment]
Its good to use this https://github.com/rafaelp/css_browser_selector for fix this type of thing. 
I didn´t have the time for doing this at the moment, but its very nice if @raimund-schluessler can do it. :)

**Comment by raimund-schluessler** [comment]
I guess this is more or less obsolete now. With current Firefox ESR 52.0 the website is shown correctly now.
