### ISSUE TITLE
Requirements for Provider Page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#395]
I dont want to discuss who is a provider - and who not 😁 I just want to create and consider about a list of requirements for the descriptions, pictures and presentations for the providers, to hold the quality of the page 😉 

### Trademark stuff

- **Spell Nextcloud** the correct way (not NextCloud, nextCloud or even nextcloud)
- Description should not contain any **other trademarks** like another cloud software.
- Picture should **only include the logo** - not the Nextcloud logo.

### Advertisement

- Description and picture should not contain **pricing and detailed offering stuff** - only a description of what your company or provider is doing.

### Country

- **Description must be in English**, otherwise, it looks messy if there are dozens of languages - multiple langs could be handled by website translation later - but for now: Lets conclude with English
- As **country** you are only allowed to select the country your company has an office, a datacenter or business-relations with... don't mass-select every country. For international support, please use "all" - for Europe, please use "eu". This would prevent from providers using "de", "ch", "fr", "au", "eu", "es" and "eu" to communicate that they are providing for the whole "eu".

Any suggestions? What do you think? @jospoortvliet

**Comment by MariusBluem** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
sounds all reasonable. what donyou think @jospoortvliet ?

**Comment by jospoortvliet** [comment]
Yeah, agreed. We should add these to the apply page. Willing to do that, @MariusBluem ??

**Comment by MariusBluem** [comment]
Will be done soon ... I am going to contact you about the providers not fulfill to the requirements.

**Comment by MariusBluem** [comment]
Done.
