### ISSUE TITLE
Outlook page - partially not readable

### ISSUE THREAD

**Issue by schiessle** [nextcloud/nextcloud.com#396]
See:

![outlook](https://cloud.githubusercontent.com/assets/1589737/22704983/010f6252-ed6a-11e6-8db8-7303d7c302e4.png)

Complete text should be:
"Pricing for the Nextcloud Secure Sharing Outlook Add-in starts at USD 5 per user per year with discounts for larger user numbers. It is currently only available as part of a Nextcloud Support Subscription."

But the part which is a link has almost the same color as the background.

**Comment by MariusBluem** [comment]
Reproducable with Sarari, Firefox and Chromium 😉

**Comment by jospoortvliet** [comment]
Fixed!
