### ISSUE TITLE
Why WordPress vs Statically Generated Website?

### ISSUE THREAD

**Issue by felicianotech** [nextcloud/nextcloud.com#397]
I am curious if anyone from the team has considered running NextCloud.com as a statically generated website? Coming here to contribute, I was surprised to see that it's a WordPress site.

Argument for statically generated: https://www.sitepoint.com/7-reasons-use-static-site-generator/

Best (IMO) to use: [Hugo](http://gohugo.io/) or [Jekyll](https://jekyllrb.com/).

Of course, switching over would be a lot of work, but I am willing to help spearhead this.

---
Part of the reason I bring this up is because I noticed there's isn't any CI/testing for this site. I'm sure we could figure out some ways to test a WordPress site but testing a statically generated site is so much easier.

Thoughts? Discussion?

**Comment by LukasReschke** [comment]
The Why: "Because it was started that way and nobody of us had time to migrate away from it" 😉

**Comment by MariusBluem** [comment]
I think this would require really a lot of work and is out of scope for now. Closing.
