### ISSUE TITLE
Internal Server Error by Installation

### ISSUE THREAD

**Issue by herbert56** [nextcloud/nextcloud.com#407]
Hi guys.
I get this error after the admin register site:
`Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
Bitte wenden Sie sich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, geben Sie bitte die, unten stehenden, technischen Details in Ihrem Bericht mit an.
Weitere Details können im Serverprotokoll gefunden werden.`

`Technische Details
Entfernte Adresse: 192.168.162.30
Anfragekennung: dFsb5FeeC+TL2LkvR1Jv`

Here is my log:
` {"reqId":"+nezOgEm4DIYXvsHheEc","remoteAddr":"192.168.162.30","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_storages` (`id`,`available`) SELECT ?,? FROM `oc_storages` WHERE `id` = ? AND `available` = ? HAVING COUNT(*) = 0' with params [\\\"home::Madin\\\", 1, \\\"home::Madin\\\", 1]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'available' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/db\\\/connection.php(206): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/db\\\/adapter.php(94): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/db\\\/connection.php(244): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*storage...', Array, NULL)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/cache\\\/storage.php(64): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*storage...', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(95): OC\\\\Files\\\\Cache\\\\Storage->__construct(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/storage\\\/home.php(76): OC\\\\Files\\\\Cache\\\\Cache->__construct(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(382): OC\\\\Files\\\\Storage\\\\Home->getCache('', Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/config\\\/usermountcache.php(92): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache()\\n#10 [internal function]: OC\\\\Files\\\\Config\\\\UserMountCache->OC\\\\Files\\\\Config\\\\{closure}(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/config\\\/usermountcache.php(93): array_filter(Array, Object(Closure))\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/config\\\/mountprovidercollection.php(98): OC\\\\Files\\\\Config\\\\UserMountCache->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/filesystem.php(436): OC\\\\Files\\\\Config\\\\MountProviderCollection->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/files\\\/filesystem.php(354): OC\\\\Files\\\\Filesystem::initMountPoints('Madin')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/util.php(220): OC\\\\Files\\\\Filesystem::init('Madin', '\\\/Madin\\\/files')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/user.php(169): OC_Util::setupFS('Madin')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/setup.php(368): OC_User::login(*** username and password replaced ***)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/core\\\/controller\\\/setupcontroller.php(65): OC\\\\Setup->install(Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(919): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2017-02-16T16:05:52+00:00","method":"POST","url":"\/nextcloud\/index.php","user":"--"}`

Here is my config:
`<?php
$CONFIG = array (
  'instanceid' => 'ocbdawzihq8k',
  'passwordsalt' => 'ZojJo3XzV5GAEJwA73UoRsFShcaWdU',
  'secret' => 'qhEtKhdcT6BnGYYUdVkAXO2hEz/5sRLWYbWthKKturT9ibyS',
  'trusted_domains' => 
  array (
    0 => '192.168.162.20:443',
  ),
  'datadirectory' => '/media/8b377d68-1c88-4857-a7f7-ee7e8a8051ac/NextCloud',
  'overwrite.cli.url' => 'http://192.168.162.20:443/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.0.54.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'xxxxxxxxxx',
);`

Can you Help me pls fast. I need my Calender!

**Comment by Espina2** [comment]
Do you have WordPress installed?

**Comment by jospoortvliet** [comment]
I think this isn't a question about the website, is it? But a Nextcloud report? I suggest you ask on the forums at https://help.nextcloud.com
