### ISSUE TITLE
Text color is too bright, insufficient contrast

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#414]
The new lighter grey text color is very difficult to read. Wasn’t it darker before?

Currently it’s `rgb(156, 156, 156)`. Can we use the same color as used elsewhere `rgb(85, 85, 85)`? It looks much nicer and readable.

cc @Espina2 @nextcloud/designers @nextcloud/website

**Comment by Espina2** [comment]
Yes, it is darker but it doesn't have enough contrast. What I suggest is to make it lighter and increase the black in the grey. I will do that.
