### ISSUE TITLE
Content initially shown directly, then flashed away, then faded in again

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#415]
This happens on every page and looks strange:
https://cloud.jancborchardt.net/s/ILN4zJnH8upREwV

cc @Espina2 @nextcloud/website @nextcloud/designers

**Comment by Espina2** [comment]
Its probable due to the original state of the document doesn't have opacity 0 so when it load the javascript file it adds animate from opacity 0 to 1. I will check this when I have free time.

**Comment by jospoortvliet** [comment]
It still happens on the Enterprise page somehow.
