### ISSUE TITLE
Multi Tennancy

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/nextcloud.com#435]
Is it possible to setup one instance of nextcloud with multiple tennants?
I know I can setup for multiple domains, but I mean multiple domains with their own theming and isolated user groups? Or would this be a new possible feature?

**Comment by Espina2** [comment]
Hi @pieter-groeneweg this repo is about the nextcloud website only. I think you will have better response on https://help.nextcloud.com/.

**Comment by pieter-groeneweg** [comment]
whoops in wrong thread.... my bad
