### ISSUE TITLE
Grammar errors on public facing NC communications

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/nextcloud.com#437]
Hey everyone. I just read the new blog post at https://nextcloud.com/blog/where-should-healthcare-data-be-stored/

I have to say, the content of this post is good. I also completely understand the steep challenges of creating professional level content in a language which isn't native to the writer. That said, I'm frequently surprised at the basic English grammar mistakes in Nextcloud blog posts given that we're aiming at an Enterprise market.

Take this single sentence for example:

> Black hats hackers are very conscious of these facts: they know medical organizations are very likely to pay any ransom if their patients life is at risk.

It's right near the start, so it's establishing for the new reader whether the rest of the article has credibility or not, and yet in one sentence there's already two basic errors which make it feel strange and uncomfortable to any native English speaker:

1. It misses that it's "black **hat** hackers" (no need to double pluralize it) and 
2. It's "if their patients lives **are** are risk" (there's more than one life that we're talking about).

There are other errors in the article too, but you get the idea.

Now, I don't want to point out errors just for the sake of making anyone wrong. I wouldn't have even brought this up if I hadn't seen a consistent pattern of errors like this in published blog posts. Everyone makes small mistakes from time to time. Everyone at Nextcloud also seems to speak English 1000 times better than mein sehr, sehr gebrochener Deutscher (my very, very broken German)! I have nothing but respect here! I just care about Nextcloud, and it's adoption. As an ex-copywriter, I've seen the data on how these "small" errors can have a big impact on new lead perception and sales, especially when it comes to first contact with leads from corporate markets.

My suggestion would be to, at the very least, install something like the free Grammarly browser extension which will pick up a lot of these basic errors for you (think of it like CI for English writing ;-) ). Preferably though, also run blog posts by someone with native English writing experience, before publishing (kind of like LGTM for English writing, to stretch the metaphor). If you need some community assistance with looking over public facing text, by all means feel free to ask me for help any time, too.

Maybe we could run blog posts through Github here too, and have some process for approval before they go live.

**Comment by jospoortvliet** [comment]
Hi Bugsbane,

Thanks, you're right, we could do a better job at getting stuff reviewed. I used to post things in the irc channel before promoting, I guess I should re-kindle that effort.

Besides that, your suggestion to install the Grammarly browser extension is a good one and we'll do this. 

Thanks!

**Comment by MariusBluem** [comment]
...and of course, we are happy if you contribute by finding grammar and other language-wise mistakes on our static (non-blog) content too: https://github.com/nextcloud/nextcloud.com ✊ @Bugsbane
