### ISSUE TITLE
https://nextcloud.com/enterprise/ top img is broken on mobile

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#440]
![spectacle y29021](https://cloud.githubusercontent.com/assets/551757/24577249/93410778-16ca-11e7-9a3b-05c3fa34935e.png)

**Comment by MariusBluem** [comment]
I can not longer reproduce this issue ... maybe it was fixed some commits ago? 🤔 Please reopen, if this is still the current behavior 😉 @jospoortvliet
