### ISSUE TITLE
fix box page on 5.5 inch devices

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#441]
as the title says.

**Comment by MariusBluem** [comment]
Have you an example screenshot?

**Comment by jospoortvliet** [comment]
![screenshot_2016-11-27-22-16-00_com android chrome](https://cloud.githubusercontent.com/assets/551757/24618710/45387e56-1898-11e7-8b96-d5a032ecac1c.png)
![screenshot_2016-12-12-16-32-12_com android chrome](https://cloud.githubusercontent.com/assets/551757/24618712/46ce327e-1898-11e7-94b1-ef7efc5f863b.png)
![screenshot_2016-12-12-16-32-32_com android chrome](https://cloud.githubusercontent.com/assets/551757/24618713/4890d7e2-1898-11e7-8eb1-5917ccf54031.png)

![screenshot_2016-12-12-16-32-43_com android chrome](https://cloud.githubusercontent.com/assets/551757/24618722/4c9443ce-1898-11e7-941c-5c1e2aa3cde9.png)

It is possible this is addressed already though. Just want to record the issue here as reported to me by mail quite a embarrassing while ago :disappointed:

**Comment by Espina2** [comment]
I will take a look at this, since I made the page.

**Comment by jospoortvliet** [comment]
any progress? It works for me - as said - but not everywhere :(

**Comment by Espina2** [comment]
It will be hard to see progress in the next two weeks, since I have with a lot of work.

**Comment by jospoortvliet** [comment]
Tested on staging, looks good to me. @mikebabb sorry it took so long but it's going live now!
