### ISSUE TITLE
https://nextcloud.com/collaboraonline/ typo "seperated"

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/nextcloud.com#442]
Where can I find the source code for the page https://nextcloud.com/collaboraonline/ ? There's a typo on it ( s/seperated/separated/ ).

**Comment by MariusBluem** [comment]
Here: https://github.com/nextcloud/nextcloud.com/blob/master/page-collaboraonline.php

**Comment by Wikinaut** [comment]
fixed in https://github.com/nextcloud/nextcloud.com/commit/40542ef6d4e9539f288104eb8bbed88fb49c0459
