### ISSUE TITLE
Update permissions script? 

### ISSUE THREAD

**Issue by purplevegetable** [nextcloud/nextcloud.com#456]
Hello, I've noticed that nextcloud complains that it finds the folder "assets" each time I update. I've deleted the folder as there doesn't appear to be anything in it so I imagine it's a redundant folder? 

Your permission script found [here](https://docs.nextcloud.com/server/9.0/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions)  re-adds the folder, not really a problem but it would save everyone who uses the script from deleting the folder once they need to update their installation.

**Comment by jospoortvliet** [comment]
Hi @purplevegetable sorry - this is where we develop our website, not the place for bug reports about Nextcloud!

Also, we no longer recommend to use the permission changes as they provide no real security benefit and block Nextcloud from upgrading. I suggest to not use it.
