### ISSUE TITLE
link more prominently to the app store

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#458]
Our navigation should link to the app store on apps.nextcloud.com. Where would that fit best?

**Comment by MariusBluem** [comment]
Wait for that and do this together with https://github.com/nextcloud/appstore/issues/468 😉

@BernhardPosselt @Espina2

**Comment by Espina2** [comment]
This is good question indeed, at least we should show the link on the footer for now? Maybe under resources? @jospoortvliet @MariusBluem

**Comment by MariusBluem** [comment]
Maybe with moving something from Resources to Interact, so that every column has the same number of links ;)

**Comment by Espina2** [comment]
If it makes sense, it's okay for me. :)

**Comment by jospoortvliet** [comment]
done in https://github.com/nextcloud/nextcloud.com/commit/e66846ec58af4513a8e4b4b58707251ac5de4fba but that's not SUPER prominent. It is now in the footer...

I just don't want to add it to the features menu and it makes no sense in the other menus. So this is it.

**Comment by Espina2** [comment]
@jospoortvliet Nice. ;)
