### ISSUE TITLE
Switch earlier to the responsive "sandwich" menu 

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/nextcloud.com#46]
With Safari on my iPad Pro 9.7, the menu is in a wrong position, if i take the iPad horicontal. I think we should go for the "sandwich" menu here :wink: 

![image](https://cloud.githubusercontent.com/assets/19711361/16495521/2b11644a-3eee-11e6-8788-ac268f5e0f39.png)

@nextcloud/designers

**Comment by jospoortvliet** [comment]
probably a tiny sizing issue but - no idea how to fix it without being able to use 'inspect' on an ipad :-1:

**Comment by mikebabb** [comment]
Not on my computer at the moment so I can't check the site's code, but it should be easily fixable by changing the cutoff point where the mobile menu is no longer used. iPad portrait tends to be 768px I think? If no one else gets to it first, I can look in to it over the weekend.

**Comment by jospoortvliet** [comment]
@mikebabb if you have a device to test that probably helps, I don't :cry:

**Comment by mikebabb** [comment]
@jospoortvliet @williambargent It even attempts a bit of touch emulation which can come in handy for testing touch device only enhancements. How effective it is I don't know, but for troubleshooting layout bugs like this one dev tools gets the job done

![screenshot from 2016-07-04 09 49 42](https://cloud.githubusercontent.com/assets/1648598/16555503/e36823f4-41cc-11e6-9ac3-cd153dd6fb98.png)

**Comment by williambargent** [comment]
@mikebabb  I have been using it form a year or two and works perfectly. If I can test it on a physical device I usually do after.
