### ISSUE TITLE
Safari issues with new homepage

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#463]
This is definitely **not**, how it should look like 😅 @jospoortvliet @Espina2 

![bildschirmfoto 2017-05-03 um 17 37 19](https://cloud.githubusercontent.com/assets/19711361/25668528/36a630c6-3027-11e7-921e-568e91f416c9.png)

**Comment by Espina2** [comment]
Can you please try it on private mode? I have no problens in safari
![screen shot 2017-05-03 at 18 36 11](https://cloud.githubusercontent.com/assets/11150206/25674115/a66bd7f8-3031-11e7-8650-877c7761d347.png)

**Comment by enoch85** [comment]
I have the same issues on Chrome (inside a Windows 10 VM)
![nextcloud_com](https://cloud.githubusercontent.com/assets/4511254/25916505/21977fde-35c5-11e7-8e72-566e11a45302.png)

**Comment by Espina2** [comment]
weird. Can anyone with windows see what is the problem?

**Comment by jospoortvliet** [comment]
Couldn't we turn the background in a png perhaps? Pre-rendered...

**Comment by Espina2** [comment]
I can take a look on this, but I need more info where this occurs.

**Comment by Espina2** [comment]
Can I close this up? @MariusBluem @enoch85

**Comment by enoch85** [comment]
@Espina2 Nope, still same issue when I was trying on the same Windows VM.

**Comment by Espina2** [comment]
I will install the VM and try see what is causing this.

**Comment by enoch85** [comment]
http://i.imgur.com/Vy4beWG.png

**Comment by Espina2** [comment]
Let me see the chrome version to @enoch85

**Comment by enoch85** [comment]
@Espina2 Ha! I had Chrome 58.something.something but updated to 59 and now it works!

**Comment by Espina2** [comment]
@enoch85 this should not be broken in that case to... I'm searching for the problem since it occurs in more browsers.

**Comment by Espina2** [comment]
I test on Windows VM I dont have the problem in any browser. Even internet explorer works. 

@MariusBluem can you confirm if it still happens in your browser??

**Comment by Espina2** [comment]
Closing this now. If it reappears please reopen.
