### ISSUE TITLE
More infos about android privacy

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/nextcloud.com#465]
Ref: https://help.nextcloud.com/t/privacy-is-my-information-harvested/12429

We should say more clearly what the android app is doing on https://nextcloud.com/privacy:
- in general: only communication between device and nextcloud server
- play store version: comm. with google server due to push notification (in 1.5.0)
- fdroid: no google server communication

Google somehow enforces a privacy policy, which is explained here http://www.iubenda.com/blog/privacy-policy-for-android-app/
I think we have most of the stuff already in our subpage. But it would be great if someone with more (lawyer) knowledge can have a look into it and point out what is missing.

**Comment by jospoortvliet** [comment]
fixed in https://github.com/nextcloud/nextcloud.com/commit/b228df32eb4f4ea66879b1c60a9101b9ac5455e9

**Comment by tobiasKaminsky** [comment]
:+1:  Perfect :-)
