### ISSUE TITLE
Clients install page is broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud.com#467]
The install page for clients https://nextcloud.com/install/#install-clients looks kinda broken to me:
![bildschirmfoto am 2017-05-18 um 17 12 32-fullpage](https://cloud.githubusercontent.com/assets/2496460/26206358/49f7c000-3bed-11e7-8cb6-a2358c5fad9f.png)

I think the popup should look similar to the one for downloading the server (darker background for the rest of the page). Also the layout of the download buttons is broken.

This is on latest Firefox 53.0.2, latest Chrome looks the same.

Maybe similar to https://github.com/nextcloud/nextcloud.com/issues/190

**Comment by jospoortvliet** [comment]
Fixed. Thanks for reporting and sorry it took so long 👎
