### ISSUE TITLE
Secure Drop -> File Drop

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#469]
According to https://github.com/nextcloud/server/pull/4943, please update the page, or (I would prefer) merge it with sharing 😉 

@jancborchardt @jospoortvliet

**Comment by jancborchardt** [comment]
@MariusBluem this is a nice starter issue, simply need to change the wording. :)

**Comment by jospoortvliet** [comment]
mostly done now. The video has to be updated, will do when I find time ;-)

**Comment by MariusBluem** [comment]
Main issue is fixed now 😉
