### ISSUE TITLE
nextcloud

### ISSUE THREAD

**Issue by a506488043** [nextcloud/nextcloud.com#470]
Install plug-ins, prompted errors, how to solve this? And upload pictures, prompt file 0KB?
Newly installed. A lot of places don't quite understand。
How do my upload this picture?
[My blog](www.saiita.cn)

**Comment by MariusBluem** [comment]
This is the repository of the homepage nextcloud.com. Please report your issue in the server-repository over here: https://github.gom/nextcloud/server/issues 🙈

**Comment by a506488043** [comment]
Ok,Thank you
