### ISSUE TITLE
Download newer than available changelog

### ISSUE THREAD

**Issue by pludi** [nextcloud/nextcloud.com#473]
The download already points to the NC12 release, while the [changelog](https://nextcloud.com/changelog/) still lists 11.0.3 as current.

**Comment by pludi** [comment]
See also nextcloud/server#5032

**Comment by jospoortvliet** [comment]
Yeah, sorry - bit overloaded with work. We'll get to this, hopefully this week ;-)

**Comment by hajika** [comment]
and https://download.nextcloud.com/server/installer/setup-nextcloud.php still points to NC 11, thats very pity

**Comment by MariusBluem** [comment]
> and https://download.nextcloud.com/server/installer/setup-nextcloud.php still fetches NC 11, thats very pity

Will be fixed with 12.0.1 🙈
