### ISSUE TITLE
Migration instruction fools admins to upgrade to incompatible owncloud before migration

### ISSUE THREAD

**Issue by Morganlej** [nextcloud/nextcloud.com#496]
It have happened with earlier versions and now happen again [1]. In short:
Instruction say latest pint releases should be used, so admin upgrades ownCloud 9.1.5 to 9.1.6.
Then he tries to migrate to Nextcloud 10.0.5, which fails with:
"Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.6.2 to 9.1.5.2)" [2]

That is what happens when we follow the instruction. https://nextcloud.com/migration/
The needed Nextcloud 10.0.6 is available "when it is done", so what the admin should have done was NOT upgrade ownCloud to last point release, but instead **upgrade ownCloud to the point release that *corresponds* to the last point release of available _Nextcloud_**, before migrating to Nextcloud.

[1] https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523
[2] That error message could use a bit more text to explain that it cryptically express itself (10.0.5) like owncloud numbering as "9.1.5.2" but that is a sidenote here...

**Comment by linucksrox** [comment]
My first thought would be channging this

> ownCloud 9.1.x is compatible with Nextcloud 10.0.x

To this

> ownCloud 9.1.0 - 9.1.5 is compatible with Nextcloud 10.0.x

Or something along those lines, so that when new ownCloud versions are released, the documentation technically doesn't address them yet, prompting administrators to do more investigation first.

**Comment by Morganlej** [comment]
The instruction then need also to describe how an admin would go about to find out compatibility for a ownCloud version not included in that definition.

**Comment by Espina2** [comment]
This question should be made in the server repo. Going to close the issue.
