### ISSUE TITLE
Migration script downloads incompatible Nextcloud version

### ISSUE THREAD

**Issue by Morganlej** [nextcloud/nextcloud.com#497]
It should better check compatibility *before* downloading or doing anything else.
Example: Currently ownCloud 9.1.6 is latest point release, and corresponding Nextcloud (10.0.6) do not exist yet.
Real world example: https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523

**Comment by linucksrox** [comment]
I think this belongs in the nextcloud/server repository. I also think the file that performs this check is located at /server/lib/private/Updater.php on lines 205-222.
https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/Updater.php#L205-L222
