### ISSUE TITLE
Syntax error on footer.php

### ISSUE THREAD

**Issue by ldonis** [nextcloud/nextcloud.com#5]
There is a little error on the documentation menu, the end tag for the html list is not commented.
![error](https://cloud.githubusercontent.com/assets/2887823/15893661/655413a8-2d3e-11e6-8e7e-356b95a78f60.png)
[templates/footer.php](https://github.com/nextcloud/nextcloud.com/blob/master/templates/footer.php)

**Comment by jancborchardt** [comment]
@ldonis good catch! Do you just directly want to fix it and open a pull request? That would be awesome! :)

**Comment by ldonis** [comment]
I just sent the pull request :D

**Comment by jancborchardt** [comment]
Thanks a lot! :) Closing this here then cause the pull request is merged.
