### ISSUE TITLE
Add link to Github on help.nextcloud.com

### ISSUE THREAD

**Issue by enoch85** [nextcloud/nextcloud.com#513]
https://help.nextcloud.com/t/welcome-to-the-nextcloud-forums/8

Many users post issues reports on the help forum that really should be on Github instead. Proper tagging and milestones will make it easier for Nextcloud devs to find and fix the issue.

**Comment by jospoortvliet** [comment]
Actually we prefer to have less technical users discuss on help.nextcloud.com first to see if the issue is already reported. help.nextcloud.com helps find duplicates, unlike github where our devs can't handle hundreds of duplicates manually.
