### ISSUE TITLE
Link the VM as an option to download

### ISSUE THREAD

**Issue by enoch85** [nextcloud/nextcloud.com#52]
As I'm sure there are many out there that started just like me, regular Windows user with no experiance in Linux at all - I think it would be a good idea to link [the VM](https://github.com/nextcloud/vm) on the download page. I also think this would involve more people to work on the VM as a community rather than I do it myself (with help from a _few_ other contributors)

Easy to install, can be run under existing Windows and everything is pre-configured.

It would also be great if every release triggered some Github magic so that the new version was linked on the download page every time a new version of the VM was uploaded.

What do you think everyone? 

cc @MorrisJobke @jospoortvliet @LukasReschke @jancborchardt and others

**Comment by MariusBluem** [comment]
Done for a while. 👊

**Comment by enoch85** [comment]
Thanks, had forgot.
