### ISSUE TITLE
Error page is broken

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#532]
As you can see in the screenshot the error page seems broken. It looks ugly and the footer isn´t showing up.

Example: https://nextcloud.com/feasas

![Error Page](https://user-images.githubusercontent.com/1869584/28452772-80a36d1e-6df4-11e7-9df7-38eb5dfd05e1.png)

**Comment by splitt3r** [comment]
And this https://github.com/nextcloud/nextcloud.com/blob/master/assets/files/request_form.pdf file is still owncloud branded.

**Comment by MariusBluem** [comment]
> And this https://github.com/nextcloud/nextcloud.com/blob/master/assets/files/request_form.pdf file is still owncloud branded.

Even if this issue is not related (and should be posted in another issue) is this nothing we need to worry about, since this file is not in use 😉 ... Maybe we can delete it? @jospoortvliet 

...do you want to jump in creating a nicer 404-page? 😊 @Espina2

**Comment by Espina2** [comment]
@MariusBluem 
We should do both things. :)

**Comment by jospoortvliet** [comment]
Yeah, just delete the file.

**Comment by Bentong021** [comment]
https://github.com/nextcloud/nextcloud.com/issues/532
