### ISSUE TITLE
Security Scan not working

### ISSUE THREAD

**Issue by JMCA2** [nextcloud/nextcloud.com#535]
From: https://help.nextcloud.com/t/nextcloud-security-scan-scan-failed/18579

> When trying to test the security of my Nextcloud installation using https://scan.nextcloud.com/6 I receive the following error:
> 
> Scan failed! The scan for the specified domain failed. Either no Nextcloud or ownCloud can be found there or you tried to scan too many servers.
> I’ve tried several times and it never works. I’ve made sure the URL is correctly typed and publicly accessible.
> 
> Any ideas?
> 
> Shared Hosting
> Nextcloud version: 12
> Apache: 2.4 (CloudLinux)
> PHP version: 7.1

**Comment by jospoortvliet** [comment]
At the moment the scanner is down - the website works but the actual scans don’t happen. They will come back up - time is needed ￼

https://help.nextcloud.com/t/nextcloud-security-scan-scan-failed/18579/9?u=jospoortvliet

**Comment by cmroanirgo** [comment]
Perhaps a message stating that the scanner is inactive might be helpful... ? I'm here because of exactly the same problem.

**Comment by jospoortvliet** [comment]
Yeah, it was meant to be up again but we're kind'a fighting a provider who's blocking or something like that, I dunno the details. @LukasReschke
