### ISSUE TITLE
Find out why and how you should upgrade to Nextcloud 11 to keep your data secure.

### ISSUE THREAD

**Issue by enoch85** [nextcloud/nextcloud.com#547]
On https://scan.nextcloud.com.

cc @MorrisJobke @jospoortvliet

**Comment by enoch85** [comment]
Didn't find the correct page in this repo, so couldn't fix it. :/

**Comment by MorrisJobke** [comment]
Do it via the build-in updater: https://docs.nextcloud.com/server/12/admin_manual/maintenance/update.html

**Comment by enoch85** [comment]
This is an error on the page, not my server. ;)Best regardsDaniel HanssonTech and MeSent from mobile, sorry for typos.Den 8 aug. 2017 10:51 fm skrev Morris Jobke <notifications@github.com>:Do it via the build-in updater: https://docs.nextcloud.com/server/12/admin_manual/maintenance/update.html

**Comment by MorrisJobke** [comment]
I will update that page.
