### ISSUE TITLE
Fix lower case page titles

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#55]
It should be `About - Nextcloud | Nextcloud` (https://nextcloud.com/about) but at some pages, it is more like: `support | Nextcloud` (https://nextcloud.com/support) 

cc @jospoortvliet

**Comment by thelinuxfr** [comment]
Hi, other relevant pages : 

- https://nextcloud.com/enterprise/
- https://nextcloud.com/contributors/
- https://nextcloud.com/jobs/
- https://nextcloud.com/privacy/
- https://nextcloud.com/press/

**Comment by jospoortvliet** [comment]
Thanks @mar1u5 and @thelinuxfr I've fixed all those you found.

**Comment by thelinuxfr** [comment]
Hi,
others more : 
- https://nextcloud.com/workflow/
- https://nextcloud.com/sharing/
- https://nextcloud.com/spreedbox/
- https://nextcloud.com/webrtc/
- https://nextcloud.com/collaboraonline/

**Comment by MariusBluem** [comment]
😒 ... Thank you for your report 😜 @jospoortvliet

**Comment by tflidd** [comment]
I checked the sites in this post but the titles have changed completely. Am I getting this wrong or can we close this topic?

**Comment by jospoortvliet** [comment]
Yeah, they should be fixed.
