### ISSUE TITLE
Website performance, delay loading javascript

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#553]
Currently the site takes very long to load. Even on wifi this is especially noticeable on mobile. One big reason is the huge amount of Javascript libraries.

We should improve here. One thing could be to load the Javascript libraries in the footer only so it doesn’t block content loading.

cc @nextcloud/javascript @nextcloud/website

**Comment by MorrisJobke** [comment]
Or have a detailed look at https://www.webpagetest.org/result/170814_2M_d9cc372131730bc20e0eb816ab4c3f53/ for the reasons of slow loading stuff. 😉

**Comment by MorrisJobke** [comment]
> One big reason is the huge amount of Javascript libraries.

The biggest problems are 6 really slow loading images. :/ The JS seems to be the smallest problem.

**Comment by Bentong021** [comment]
https://github.com/nextcloud/nextcloud.com/pull/434

**Comment by MorrisJobke** [comment]
@Bentong021 why are you posting unrelated stuff in a lot of tickets. I will delete your comment here.

**Comment by jancborchardt** [comment]
@MorrisJobke lso saw @Bentong021’s comments in 2 other issues, assume spammer, reported to Github.

**Comment by jancborchardt** [comment]
@MorrisJobke also added the account to blocked users: https://github.com/organizations/nextcloud/settings/user_blocks just in case that happens again and we quickly need to block.

**Comment by jospoortvliet** [comment]
I can't really read the performance test thingy - what 6 images are super slow? I can perhaps make them smaller, optimize them?

**Comment by jospoortvliet** [comment]
Ah jezus we have a 3.2MB svg on our home page... At least that can be fixed: #557

**Comment by Espina2** [comment]
@jancborchardt @MorrisJobke @jospoortvliet 
https://github.com/nextcloud/nextcloud.com/issues/553

The biggest problem is the huge amount of http requests. In the PR above I made a lot of changes, I just don't have the time for end that now. Maybe something I can do next week at the conference.

**Comment by jospoortvliet** [comment]
A lot of this was done, so let's close this.
