### ISSUE TITLE
Add seafile to comparison chart

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#561]
ref: https://help.nextcloud.com/t/please-also-add-seafile-to-the-comparison/19889

**Comment by MariusBluem** [comment]
@jospoortvliet SeaFile has an professional edition, which we can compare with. Your choice 😉

**Comment by jospoortvliet** [comment]
Seafile is entirely irrelevant on the market so no, we're not going to bother 😄 We don't lose customers to Seafile, ever...  If we start to, perhaps we can add them.

But now, this would essentially just give them more attention than, from a competition point of view, they are worth. The rule with comparisons is: put those on there you WANT to be compared to.
