### ISSUE TITLE
Use new Google Play button

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#564]
Current:
<img width="230" alt="bildschirmfoto 2017-08-24 um 12 13 48" src="https://user-images.githubusercontent.com/19711361/29661899-beafae88-88c5-11e7-8c4d-6605957798a4.png">

How it should be: https://play.google.com/intl/en_us/badges/

@jospoortvliet

**Comment by jospoortvliet** [comment]
Sneaked in a fix in https://github.com/nextcloud/nextcloud.com/pull/580

**Comment by MariusBluem** [comment]
Great.
