### ISSUE TITLE
[scan.nextcloud.com] Rescan of websites doesn't work

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/nextcloud.com#587]
I report the issue here as I don't know of any better place for problems with [scan.nextcloud.com](https://scan.nextcloud.com/).

Rescan of Nextcloud Instances doesn't work. It claims that rescan is triggered and takes up to five minutes, but nothing happens.

I tried with our Nextcloud Instance `cloud.systemli.org`:
https://scan.nextcloud.com/results/016708cf-106c-4731-8745-6a834c7dfa6b

**Comment by jospoortvliet** [comment]
Should be fixed!
