### ISSUE TITLE
Picture is missing

### ISSUE THREAD

**Issue by Tanarri** [nextcloud/nextcloud.com#590]
Hi,

on the page https://nextcloud.com/release-channels/ there is a big blank space on top of the page.
I think there should be a picture, which is actually missing
![grafik](https://user-images.githubusercontent.com/6181166/30613942-21d1e58e-9d8a-11e7-9602-35d766255c0b.png)

Greetings
Eugen

**Comment by jospoortvliet** [comment]
Yeah, javascript is broken on the page. @Espina2 can you fix this perhaps?

**Comment by Espina2** [comment]
Currently are fixed.
