### ISSUE TITLE
App Generator creates faulty info.xml when using umlauts (special characters äöü)

### ISSUE THREAD

**Issue by Dexter2k** [nextcloud/nextcloud.com#599]
Problem: nextcloud/apps/foo/appinfo/info.xml misses the closing **</info>** tag. Just generates **</**

Steps to reproduce:

- visit https://apps.nextcloud.com/developer/apps/generate
- enter the required information; in summary and description enter "This is a test app äöü"
- click generate and download.
- look at the generated info.xml

**Comment by splitt3r** [comment]
You should post that over at https://github.com/nextcloud/appstore

**Comment by Dexter2k** [comment]
Oh, you are right, thanks. 
Issue now under: https://github.com/nextcloud/appstore/issues/522
