### ISSUE TITLE
Put warning about missing javascript a bit lower, somehow

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#600]
If you share a page on our website, often the javascript warning shows up on top. Would there be a way to put it a bit lower somehow, under other text or... I dunno... Ideas?
![screenshot_20170925_202526](https://user-images.githubusercontent.com/551757/30824424-e339e380-a22f-11e7-9bd3-7affccb5ea9d.png)

**Comment by Espina2** [comment]
@jospoortvliet You can make the alert fix. Any other thing doesn't make sense.

**Comment by jospoortvliet** [comment]
You mean doing it in CSS? so we can put it in the footer but it comes to the top of the page?

**Comment by Espina2** [comment]
Make the element position to be fixed on the top of the screen. Something like this position: fixed; top: 10px;
