### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#608]
Some of the page titles have a lot of Nextcloud in it 😄:

https://nextcloud.com/about/ => About – Nextcloud – Nextcloud
https://nextcloud.com/contribute/ => Get involved – Nextcloud – Nextcloud

The [End to end encryption](https://nextcloud.com/endtoend/) and the [Monitoring](https://nextcloud.com/monitoring/) page still needs a proper page title.

And perhaps for other pages like the following it woul also be enough to simply name them "Sharing – Nextcloud" for example:

https://nextcloud.com/sharing/ => Sharing in Nextcloud – Nextcloud
https://nextcloud.com/partners/ => Nextcloud Partners – Nextcloud

Also some of the press releases have real page title e.g. https://nextcloud.com/press/pr20160929/.

**Comment by MariusBluem** [comment]
I don’t know if it would make sense to double the trademark „Nextcloud“ in the page title.

**Comment by splitt3r** [comment]
My point is removing the double usage :grimacing:

**Comment by jospoortvliet** [comment]
Let me see if I can fix this. It's Wordpress doing this part...

**Comment by jospoortvliet** [comment]
So I went over a bunch of pages and I think this is fixed. If you see more - let me know!

Thanks!

**Comment by splitt3r** [comment]
Monitoring page title misses a d => "Monitoring an auditing" => https://nextcloud.com/monitoring/

**Comment by jospoortvliet** [comment]
Fixed a bunch more...
