### ISSUE TITLE
Providers page looks down - doesn't list providers anymore

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/nextcloud.com#615]
I tried with firefox dev edition and chromium, same result.

In the js console, I can see the following error:
```
TypeError: $.getJSON is not a function
[Learn More]
```

https://nextcloud.com/providers/

Hope it helps :)

**Comment by Espina2** [comment]
Thanks,

Fixed in PR above
https://github.com/nextcloud/nextcloud.com/pull/620
