### ISSUE TITLE
add changelog to website

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/nextcloud.com#62]
analog to https://owncloud.org/changelog/

as mentioned in https://github.com/nextcloud/server/issues/321

**Comment by mar1u5** [comment]
We would need to refactor this page, by removing all old stuff (7, 8, 8.1, 8.2 and maybe 9). After that, we need to add 9.0.50 as initial release, 9.0.51 as 2nd and so on 😉 

https://github.com/nextcloud/nextcloud.com/blob/master/page-changelog.php

Does anybody wants to take over here? 😁

**Comment by tflidd** [comment]
Seems, someone did this already. However, it would be nice to provide download links for each of these versions.

**Comment by MariusBluem** [comment]
Done ✊ https://nextcloud.com/changelog - with download links 👊
