### ISSUE TITLE
Request:  Add NextcloudPi to the Devices page.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloud.com#625]
Please add [NextcloudPi, an official Nextcloud project](https://github.com/nextcloud/nextcloudpi), to the actual website for those wanting to roll-their-own Nextcloud instance on a Pi.  It runs on both the Raspberry Pi 2 and 3 + is very easy to install.  Web and Cli admin interface makes it easy to add external drives and maintain the instance.

**Comment by MariusBluem** [comment]
The devices page is not intended for code, but for devices which provide an out of the box experience and are ready to be sold :) what do you think? @jospoortvliet

**Comment by nachoparker** [comment]
We already have an answer!

https://github.com/nextcloud/nextcloudpi/issues/249#issuecomment-338034833

Thanks everyone, I think we can close this.
