### ISSUE TITLE
Local dev env: /var/www/html/wp-content/themes/next/l10n/base folder is missing

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloud.com#635]
I try to setup a local development environment for the Nextcloud wordpress site as per documentation. I'd like to use Docker for this and in fact would like to add the instructions then to the Readme as well, if you like, because I think it might be helpful for those who'd like to add some changes / pull requests but don't want to have to setup the system for long-term but can just get rid of the docker container ones they're done.

I almost succeed with the setup but it seems that in the end, the folder `/var/www/html/wp-content/themes/next/l10n/base` is missing. Unfortunately I'm not a regular Wordpress user, so I don't know WP much.
When I open the WP website, I get a lot of error messages that are about missing files in the localization folder named `/var/www/html/wp-content/themes/next/l10n/base`, which does not exist.
I only have one single file under the `l10` folder which is named `sync.php`.

<img width="1440" alt="screen shot 2017-10-17 at 13 12 18" src="https://user-images.githubusercontent.com/295122/31662372-663a4526-b33e-11e7-8cfc-6d691d97300a.png">

<img width="614" alt="screen shot 2017-10-17 at 13 22 50" src="https://user-images.githubusercontent.com/295122/31662379-6b508264-b33e-11e7-92ba-229769131d35.png">

There are my steps:

I use a wordpress container that is based on Wordpress 4.8.2. (>= 3.8.1)

### MYSQL DOCKER
- docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d mysql

### NEXTCLOUD WEBSITE
- git clone https://github.com/nextcloud/nextcloud.com.git next

### NEXTCLOUD WORDPRESS DOCKER
- mkdir nextcloud-wordpress-docker
- cd nextcloud-wordpress-docker
- wget https://raw.githubusercontent.com/docker-library/wordpress/master/php7.1/apache/docker-entrypoint.sh
- echo $'FROM wordpress\nVOLUME /var/www/html/wp-content/themes/next' > Dockerfile
- docker build -t nextcloud-wordpress .
- docker run --name nextcloud-wordpress --link mysql:mysql -d --volume /path/to/my/local/next:/var/www/html/wp-content/themes/next -p 32770:80 nextcloud-wordpress

Manual steps I then do in wp-admin: 

- open Wordpress on http://localhost:32770
- select language, afterwards I get to wp-admin
- activate Next theme
- setup WP import tool
- import content.xml

### NEXTCLOUD WORDPRESS DOCKER (continued)
- docker exec nextcloud-wordpress cp /var/www/html/wp-content/themes/next/config.php.sample /var/www/html/wp-content/themes/next/config.php

- view the site on http://localhost:32770

**Comment by jospoortvliet** [comment]
This is the translation stuff. It works on the site, otherwise, I'm clueless... Also, sorry, never used the docker image. I know I probably should but I have a working setup and I already thank the gods for that - don't dare to touch it.
