### ISSUE TITLE
image hosting on apps page

### ISSUE THREAD

**Issue by hajika** [nextcloud/nextcloud.com#643]
Why are the images on apps page hosted on github and also private pages like passman.cc ?

https://apps.nextcloud.com/

**Comment by MariusBluem** [comment]
Not an issue within this repo. This is about the appstore (repo in nextcloud/appstore)
... the preview images are generated from the links in the info.xml file of the specific app. Where the images are hosted is the authors choice (GitHub, own server, ...)
