### ISSUE TITLE
Submenu JS errors on pricing page

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#652]
Browsing the pricing page gives me some js errors from submenu.js. Tried it with FF + Edge.

Link: https://nextcloud.com/pricing/

![Error](https://user-images.githubusercontent.com/1869584/32244180-feb6427a-be77-11e7-91e2-7d24575d9824.png)

**Comment by Espina2** [comment]
This error don't really matters. The error's appear because they dont get the top position of some element.

**Comment by jospoortvliet** [comment]
Should be far less bad now. There's still one, a 'unreferenced top' thing that I just don't understand... Pls re-open if you see more issues!

Oh and note I didn't do anything to fix it because I really don't 'do' Javascript 🌵  I just checked and the errors weren't there in chrome.

**Comment by splitt3r** [comment]
Firefox on Ubuntu still has a lot of errors once you scroll a bit more. But anyway lets close this.
