### ISSUE TITLE
Invalid links on design guidelines webpage

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloud.com#655]
@nextcloud/designers 
A few of the links under https://nextcloud.com/contribute/design/, especially under section "More concrete HTML+CSS guidelines" aren't valid anymore.

**Comment by skjnldsv** [comment]
And there is a text we should update :

> We don’t use SASS or another preprocessor because of the barrier to entry.

**Comment by MorrisJobke** [comment]
cc @jospoortvliet

**Comment by jancborchardt** [comment]
Thanks for the find! Fix is part of https://github.com/nextcloud/nextcloud.com/pull/672
