### ISSUE TITLE
Pricing page: add timezone UTC+01:00 to business hour support

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloud.com#658]
We should add the timezone (UTC+01:00 or alike) to the pricing table on https://nextcloud.com/pricing/ where it says:

> Phone Support: Business Hours
> Email Support: Business Hours

**Comment by tflidd** [comment]
@jospoortvliet Is all support based on European business hours (CET or UTC +01:00)?

**Comment by jospoortvliet** [comment]
@tflidd that is correct, yes.
