### ISSUE TITLE
Text not aligned properly on E2E page

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloud.com#682]
The text is not aligned properly on the https://nextcloud.com/endtoend/ page. Starting a paragraph with indention might be nice in print, but not for web or short paragraphs, therefore should simply be left-aligned.

![screenshot from 2017-12-04 09-43-46](https://user-images.githubusercontent.com/295122/33543626-0686d1f2-d8d8-11e7-93ee-7157b41b1be0.png)

**Comment by jospoortvliet** [comment]
Shift-refresh should make the page look like this:
![screenshot_20180122_205720](https://user-images.githubusercontent.com/551757/35241466-d8a464a6-ffb6-11e7-8593-8d6da29e2107.png)
If not, there's an issue. The checkmarks should be there 😄
