### ISSUE TITLE
Provide a help page about outdated PHP version

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/nextcloud.com#686]
We just noticed that a lot of people are stuck on Nextcloud 10. So we looked into this and found out, that those people use PHP 5.4 or PHP 5.5 and thus cannot upgrade to Nextcloud 11. Therefore I looked into how the update server can provide those users with a message to upgrade their PHP version. This message needs to be made available via an URL. I would simply put it on our web site.

@jospoortvliet is this possible?

I already drafted a little text, that maybe needs a bit of refinement. @NinaNC @jospoortvliet Could you help me here?

cc @MariusBluem @LukasReschke @rullzer Because we discussed about this.

> ### Update for your Nextcloud
>
> Hi Nextcloud user,
>
> our update check has noticed, that you are running PHP 5.4 or PHP 5.5 on your Nextcloud server. The last supported version of Nextcloud for this PHP version is Nextcloud 10. We recently stopped providing bug and security fixes to this release. Nextcloud 11 and 12 require as minimum PHP version 5.6. We want to ask you to upgrade the PHP version on your server in order to allow Nextcloud to upgrade to a more recent, stable, performant and secure version of Nextcloud. Once you upgraded the PHP version, Nextcloud will inform you about possible updates. Just go to the admin settings and check the version section.
> 
> Note: It could take up to 30 minutes until the check is executed. To force the check, switch to a different update channel, wait for the "Channel updated" message and switch back to the original channel. The available update should then be visible after a page refresh.
> 
> Kind regards,
> Nextcloud team

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/updater_server/pull/89 for the updater server PR.

**Comment by rullzer** [comment]
Looks good to me.

**Comment by jospoortvliet** [comment]
Will create a page. Address would be:
https://nextcloud.com/outdatedphp
Ok with that?

**Comment by MorrisJobke** [comment]
> https://nextcloud.com/outdatedphp

Could we make it a bit more special? Like https://nextcloud.com/outdated-php-5.4-5.5 because in the future we also want to link to a 5.6 page, but for more promotional reasons to help people before they run into problems with 14.

Does that make sense?

**Comment by MariusBluem** [comment]
Or we call it /dependencies and create ankers 🤔

**Comment by jospoortvliet** [comment]
outdated-etc works for me. it will be https://nextcloud.com/outdated-php-5-4-5-5/

PR coming.

**Comment by MorrisJobke** [comment]
> PR coming.

Thanks :)

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/pull/697
