### ISSUE TITLE
References are not grey in Safari

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#691]
Using the newest version of Safari, our client logos are not grey :( Looks strange.

<img width="1380" alt="bildschirmfoto 2017-12-10 um 22 18 30" src="https://user-images.githubusercontent.com/19711361/33809499-209b5b42-ddf8-11e7-8851-3ddb339ef581.png">

Can somebody of you take care of this? I have no plan how to fix this :( @Espina2 @jospoortvliet

**Comment by jospoortvliet** [comment]
Sigh, safari doesn't seem to support the filters I used :-1:

**Comment by jospoortvliet** [comment]
I don't know how to fix this either, but I guess we can live with the colors? At some point Safari will add this...

Or perhaps you can try https://stackoverflow.com/questions/286275/gray-out-image-with-css ??? I can't test it so there's not too much I can do.

**Comment by jasonbayton** [comment]
Would it take much effort just to replace them with greyscale versions? 5 mins in GIMP aught to do it.

**Comment by jospoortvliet** [comment]
@jasonbayton yes, that would work, but we use them in color in other places. I think it is fine in color, tbh - not a huge deal. So let's keep it as it is...
