### ISSUE TITLE
German Umlaute in Files App

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/nextcloud.com#727]
I have a problem with special characters in names of files or folders, witch were doesn’t created with the files-app.
These files came through download on the harddisk of my homeserver. The folder containing the downloaded files are configured as “local” external storage in my nextcloud.
Files and folders with german “umlaute” created by nextcloud in the files-app appear in the file listings. Other files and folders (from download) are ignored by the occ-file-scan.

While file-scan in debug mode the following messages appear in nextcloud.log.
There have to be Lügen instead of L\u00fcgen and Hölle instead of H\u00f6lle for example.

{“reqId”:“X7LIb2Ci8jdOOkqp3leZ”,“level”:0,“time”:“2017-12-26T17:25:29+01:00”,“remoteAddr”:"",“user”:"–",“app”:“OC\Files\Cache\Scanner”,“method”:"–",“url”:"–",“message”:"!!! Path ‘Serien/Zoo/S02E06.Sex, L\u00fcgen und Quallen.mp4’ is not accessible or present !!!",“userAgent”:"–",“version”:“12.0.4.3”}

{“reqId”:“X7LIb2Ci8jdOOkqp3leZ”,“level”:0,“time”:“2017-12-26T17:25:29+01:00”,“remoteAddr”:"",“user”:"–",“app”:“OC\Files\Cache\Scanner”,“method”:"–",“url”:"–",“message”:"!!! Path ‘Serien/Zoo/S02E10.H\u00f6lle in Helsinki.mp4’ is not accessible or present !!!",“userAgent”:"–",“version”:“12.0.4.3”}

While searching for a solution of this issue, i noticed that there are several other files mit these charactes in my nextcloud. I fixed this issue for the files above by renaming them in filesystem, occ files:scan and renaming again in files-app. But this doesn't solve the initial problem. What's up with that files. I'll keep the original ones for further testing.

Thanks for advice.

**Comment by MariusBluem** [comment]
This repo is only for the website nextcloud.com and not the product itself ... please reopen your issue on https://github.com/nextcloud/server - Thanks!
