### ISSUE TITLE
Menu does not work on old pages like page-install

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#736]
<img width="1313" alt="bildschirmfoto 2018-01-11 um 14 01 39" src="https://user-images.githubusercontent.com/19711361/34826747-2758e974-f6d8-11e7-898d-5a85ae0e0eae.png">

@jospoortvliet

**Comment by jospoortvliet** [comment]
Seemy comment at https://github.com/nextcloud/nextcloud.com/issues/737

**Comment by MariusBluem** [comment]
Browser: Chrome, Safari
Of course, I did clean cache and tried out private mode :roll_eyes:

**Comment by jospoortvliet** [comment]
Same in other then - @camilasan or @Espina2 ...

**Comment by jospoortvliet** [comment]
Ok, this was due to the separate css files! 🎂 
All good, this should fix it: #746
