### ISSUE TITLE
More menu issues since Products separation

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#737]
![jan -11-2018 14-04-04](https://user-images.githubusercontent.com/19711361/34826804-5c48ef8a-f6d8-11e7-94a5-169d7ee3eb7c.gif)

Would be nice if we can fix this :(( @jospoortvliet

**Comment by jospoortvliet** [comment]
Can't reproduce. At least tell me a browser. Also, shift-refresh to empty your cache. And don't resize the browser window, or if you do - refresh first, our site doesn't deal well with resizing but luckily ppl don't do that all the time.

In any case, I can't do ANYTHING to this menu, Paulo wrote it entirely in Javascript and I don't read or write that. Sorry :(

**Comment by MariusBluem** [comment]
Browser: Safari
Cache was of course deleted. No resizing :(

**Comment by jospoortvliet** [comment]
Then it is a bug, yeah, and the only person who can do something about it is @Espina2 or somebody else with javascript fu. Perhaps @camilasan feels like it, to take a break from C++?

**Comment by mathiasconradt** [comment]
Vertical spacing also differs on the home page vs. other pages like the migration page, where there is too much space between label and sublabel.

![image](https://user-images.githubusercontent.com/295122/34979520-c9adcc4a-faa1-11e7-95c2-dfebdae0ca6a.png)
