### ISSUE TITLE
Federation page needs some love

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#741]
The federation page does need some love:

![federation](https://user-images.githubusercontent.com/1869584/34895553-98f9bb6c-f7e6-11e7-8ac8-1b5c8d4a619c.png)

![border](https://user-images.githubusercontent.com/1869584/34895580-b772e578-f7e6-11e7-8ab5-2efb992ad47d.png)

**Comment by jospoortvliet** [comment]
A shift-refresh should fix this.
