### ISSUE TITLE
Comparison has some mistakes

### ISSUE THREAD

**Issue by macau23** [nextcloud/nextcloud.com#765]
It's important for Nextcloud's reputation for trustworthiness that the comparison page is correct.

I noticed that owncloud is listed as proprietary, which is not strictly true: the core is open source.

Dropbox does not require payment for automatic upload of images/video. They might qualify for local/nfs support for file storage too.

**Comment by jospoortvliet** [comment]
ownCloud Enterprise Edition is largely closed source. There is plenty proprietary software that happens to rely on some open source components - that doesnt' matter, it gives you none of the benefits of open source. Gartner has a nice analysis of that: https://blogs.gartner.com/brian_prentice/2010/03/31/open-core-the-emperors-new-clothes/
