### ISSUE TITLE
Changelog 12.0.5

### ISSUE THREAD

**Issue by MaxXor** [nextcloud/nextcloud.com#768]
In the [changelog](https://nextcloud.com/changelog/#latest12) for Nextcloud 12.0.5 is written:
- Update icewind/smb to 2.0.3
- update icewind/smb to 2.0.4

Shouldn't it contain only the most recent version when it gets changed multiple times before release?

**Comment by jospoortvliet** [comment]
It's a list of the changes... That might indeed contain semi-doubles like those, yes, but it was changed twice during development so the list is technically correct ;-)

I guess you can argue either way, I guess I can remove doubles in the future if I think of it.
