### ISSUE TITLE
Frontpage announcement has weird spacing

### ISSUE THREAD

**Issue by eppfel** [nextcloud/nextcloud.com#776]
Just a quick find:
<img width="741" alt="screen shot 2018-02-02 at 11 08 49" src="https://user-images.githubusercontent.com/1899308/35727722-c18da9d6-0811-11e8-827f-72d7be78c656.png">

It seems this is realted to the line break:
<img width="568" alt="screen shot 2018-02-02 at 12 09 11" src="https://user-images.githubusercontent.com/1899308/35727776-edd8126a-0811-11e8-96a6-d6a45dcd3237.png">

Chrome 63 on Mac 10.12.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

@nextcloud/designers

**Comment by skjnldsv** [comment]
Also at width 979 px
![capture d ecran_2018-02-03_08-41-29](https://user-images.githubusercontent.com/14975046/35765124-1350b0c2-08be-11e8-801d-ee238762fbc4.png)

**Comment by jancborchardt** [comment]
Yeah, also with the new slogan the breaks are quite unfortunate in the text, making the spacing look even stranger.
