### ISSUE TITLE
News overview page: style adjustments for news entries

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloud.com#782]
The news overview page at https://nextcloud.com/news/ looks a bit unstructured and it's hard to see where one entry ends and another begins, also because the H1-H3 are larger than the .contribook_blogheadline text.

Therefore I suggest to make all headlines on this page the same size. I think the following snippet would do.

https://github.com/nextcloud/nextcloud.com/blob/master/page-news.php

```
<style>
div.row h1, div.row h2, div.row h3 {
    font-size: 1.25em;
}
</style>

```

Also add a horizontal rule between each entries:

I guess the code for this is somewhere in the logic behind

`CONTRIBOOK_BLOG::show(($page-1)*5,5);`

**Comment by jospoortvliet** [comment]
Well, I tried to fix it... Didn't go all too well, this is messy. I guess we'll end up fixing this when we redo the site.

Meanwhile due to the website crash contribook is down and we only have nextcloud.com/blog which has none of the issues you mention.

**Comment by jospoortvliet** [comment]
the current look is entirely different, should be OK.
