### ISSUE TITLE
Link to documenation broken

### ISSUE THREAD

**Issue by abradshaw** [nextcloud/nextcloud.com#784]
Hi, when you click to download the archive, there is a link to the Next Cloud Admin manuals but this link takes you to a "file not found" page

[Admin Manual Link](https://docs.nextcloud.com/server/13.0.0/admin_manual/installation)

**Comment by MariusBluem** [comment]
@MorrisJobke Are the docs live?

**Comment by MariusBluem** [comment]
Will be fixed with https://github.com/nextcloud/nextcloud.com/pull/785

@MorrisJobke Are the docs live yet?

**Comment by abradshaw** [comment]
Looks like they arent, all the 13 links on https://docs.nextcloud.com/ are also not working, I guess they will once the docs go live

**Comment by MorrisJobke** [comment]
For now I created a symlink from 13.0.0 to 13 until we fixed the web page.

**Comment by MorrisJobke** [comment]
Fixed on our web page.
