### ISSUE TITLE
OCR App

### ISSUE THREAD

**Issue by biglioncoding** [nextcloud/nextcloud.com#789]
I am new to NextCloud, installed using docker, version 13.

I can't find the OCR app/connector in the AppStore, is that removed like Google Drive / Dropbox Sync, or I did something wrong or missing ?

Thanks.

Alex

**Comment by jospoortvliet** [comment]
There does not yet seem to be a version for Nextcloud 13 - see the versions on https://apps.nextcloud.com/apps/ocr

It is best to contact its author and ask for a new version!
