### ISSUE TITLE
Link to bug bounty program leads to 404

### ISSUE THREAD

**Issue by d-Rickyy-b** [nextcloud/nextcloud.com#793]
On the [Nextcloud Files](https://nextcloud.com/files/) site below "Security first", there is a link to the bug bounty program. That link leads to a 404 page.

This is the line of code:

https://github.com/nextcloud/nextcloud.com/blob/be9d7ec9fd57861777c5aa6edd13125ee30b9ff2/page-features.php#L93

**Comment by tflidd** [comment]
I'm redirected to this site:
https://nextcloud.com/blog/introducing-the-nextcloud-bug-bounty-program/

**Comment by d-Rickyy-b** [comment]
@tflidd Indeed, I do now too. 2 days ago there was a 404 page waiting for me when I opened the url. Seems like it's fixed. Feel free to close the issue.
