### ISSUE TITLE
PGP public key on website is not accessible (HTTP 404)

### ISSUE THREAD

**Issue by Happy86** [nextcloud/nextcloud.com#798]
Hi, 

when I try to download the public key from https://nextcloud.com/nextcloud.asc my browser displays a 404.

Best regards, 
Andreas 
![bildschirmfoto von 2018-02-16 00-27-11](https://user-images.githubusercontent.com/618847/36286514-6ecfb5d2-12b0-11e8-8249-f54df3a0a80b.png)

**Comment by Happy86** [comment]
Also this way nobody will be able to verify if the .tar.bz / .zip package was really released by you.

Is the public PGP key accessible on a keyserver? If so: What is the fingerprint of the pubkey? 

![bildschirmfoto von 2018-02-16 13-25-25](https://user-images.githubusercontent.com/618847/36308532-69eef2d2-1321-11e8-8beb-509d3e710176.png)

**Comment by d-k-c** [comment]
Thank you for reporting the issue, I was about to do the same. This is blocking the installation for me.

**Comment by Happy86** [comment]
> This is blocking the installation for me. 

Yep that is how I also noticed the problem. :D

**Comment by d-k-c** [comment]
@Happy86 the key is now online

**Comment by Happy86** [comment]
@d-k-c Thank you. 

So this issue is resolved. :-)
