### ISSUE TITLE
Update migration infos

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#800]
Recently, OC 10.0.6 and NC 13 have been released. There are already user questions popping up in the forum, how the migration works for OC 10.0.6 and if a manual upgrade to NC 12 or NC 13 is possible.

https://help.nextcloud.com/t/migrating-from-owncloud-10-x-to-nextcloud-12-x-or-not-and-if-so-how/25002

**Comment by jospoortvliet** [comment]
See https://github.com/nextcloud/nextcloud.com/pull/966 - once that is merged... this can close :D
