### ISSUE TITLE
 Nextcloud Security Scan needs some love

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#819]
- It still links to 12 docs
- https://nextcloud.com/?p=1334 does not exist anymore
- "Security Hardening Guide" links to 11 docs
- "Our recommendation" lists outdated Nc versions
- Copyright year could be updated to 2018 😀

**Comment by jospoortvliet** [comment]
* [x] It still links to 12 docs
* [ ] https://nextcloud.com/?p=1334 does not exist anymore
* [ ] "Security Hardening Guide" links to 11 docs
* [ ] "Our recommendation" lists outdated Nc versions
* [x] Copyright year could be updated to 2018 grinning

**Comment by jospoortvliet** [comment]
add to security scanner:
* [x] tweet/etc results
* [ ] subscribe to our newsletter
* [ ] subscribe to our releases newsletter

**Comment by jospoortvliet** [comment]
This will be reviewed & go live soon, so let me close this as I'll sure forget to do that!

Thanks @splitt3r
