### ISSUE TITLE
RSS feed stopped updating

### ISSUE THREAD

**Issue by EvEvans** [nextcloud/nextcloud.com#823]
New blog articles at https://nextcloud.com/blog/ do not pop up anymore at https://nextcloud.com/blogs/feed/ since 14 February 2018.

**Comment by rEnr3n** [comment]
The feed's latest entry is titled "Nextcloud 13.0.1, 12.0.6 and 11.0.8 available with improved password protection" dated March 15, 2018. The next 6 blog posts, as of this writing, are missing.

**Comment by rEnr3n** [comment]
It was fixed some days ago. Now it's broken again. The feed keeps breaking all the time.

**Comment by jospoortvliet** [comment]
fixed now.
