### ISSUE TITLE
IPv6 not supported on download.nextcloud.com

### ISSUE THREAD

**Issue by tuxis-ie** [nextcloud/nextcloud.com#831]
I noticed that (download.)nextcloud.com is lacking IPv6 support. Which requires me to fallback to IPv4. Please support IPv6 on your webservices.

**Comment by MariusBluem** [comment]
Thank you for reporting. Our sysadmin-departement knows about this and has this on its task-list for infrastructure improvements and fixes. I will close this over here, since this repository is only tracking issues for our website (https://nextcloud.com) and not for the rest of our infrastructure.
