### ISSUE TITLE
Useless form displayed at <blog url>/upload

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud.com#846]
E.g. https://nextcloud.com/blog/nextcloud-9-update-brings-security-open-source-enterprise-capabilities-and-support-subscription-ios-app/upload

Could leave Illuminati comments on our website which are not visible on the front page.

**Comment by jasonbayton** [comment]
@jospoortvliet I couldn't see anything obvious from the outside. Can you check what's happening internally within WP?

**Comment by jospoortvliet** [comment]
Ah, I figured out what it is - each page has an image associated and you can comment on images in wordpress. I believe that the comments have to be approved to show up, however, and I don't approve anything, so I think it is a nice black hole that goes nowhere...

**Comment by jospoortvliet** [comment]
Ok, I disabled comments as far as I could... should be gone now.
