### ISSUE TITLE
Providers page is broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#851]
When you go to https://nextcloud.com/providers/, no providers show up:
![providers broken](https://user-images.githubusercontent.com/925062/39017860-b4ea5996-4424-11e8-94e3-413c2fb9520d.png)

Might be related to these errors:
![screenshot from 2018-04-19 22-54-41](https://user-images.githubusercontent.com/925062/39017859-b4b706ae-4424-11e8-9182-dbb34e95397e.png)

cc @jospoortvliet @nextcloud/website

**Comment by chk1** [comment]
The SSL cert for code.jquery.com is currently broken

**Comment by jasonbayton** [comment]
Can confirm it's working fine here also. Will close this off for now.
