### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#858]
We have to make our site GDPR ready, of course. Here some things we have to look at:

# Matomo:
https://matomo.org/blog/2017/09/gdpr-potential-consequences-matomo/
* we have most stuff already set up just fine. I want to clean up old reports, but we already only store anonymized IP addresses...

# Mautic:
https://www.mautic.org/blog/marketer/mautic-and-gdpr/
* need to update our cookie collection info thingy to mention Mautic more clearly
* create a way to easily delete users and to sent info from the system.

# CDN's
We have javascript & stuff on CDN's. They get user requests for data. The web is not really clear on this: yes, an IP is user-identifiable-data, but if it isn't actually connected with any user data, nor stored or handled by you, are you responsible for anything?

# YouTube and ReCaptcha
Similar to the CDN's - we embed YouTube videos, ReCaptcha captchas etc. The web isn't clear about this, at least I can't figure out what to do with it for now. Input welcome.

**Comment by tflidd** [comment]
> We have javascript & stuff on CDN's.

Or we take this as a chance to remove it (and avoid issues like https://github.com/nextcloud/nextcloud.com/issues/851)?
https://github.com/nextcloud/nextcloud.com/issues/606



> we embed YouTube videos

automatically exposing users to google? Just a screenshot and link to the video (so people clicking on it are aware that they go to youtube)? Or if these are self-made videos, host them on our own (this project is about self hosting your data, isn't it)?

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/pull/869 fixes the CDN's and YouTube and reCaptcha.

**Comment by jospoortvliet** [comment]
als updated privacy policy, already before may 27 - forgot to close this :-1:
