### ISSUE TITLE
New collabora online variable

### ISSUE THREAD

**Issue by s-john19** [nextcloud/nextcloud.com#861]
It's about this page: https://nextcloud.com/collaboraonline/ - The new collabora online code docker image supports a new variable "dictionaries".

So now you can select the dictionaries you want with:
```
docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=cloud\\.nextcloud\\.com' -e 'dictionaries=de en es ..' --restart always --cap-add MKNOD collabora/code
```

So now you are not only limited to german, english, italian, french and spanish. I think this info should be on the website for all the people who are speaking not the "main" languages.

**Comment by jospoortvliet** [comment]
@s-john19 you are very much right! Any chance you could edit the file:
https://github.com/nextcloud/nextcloud.com/blob/master/page-collaboraonline.php
and do a PR?
