### ISSUE TITLE
Nextcloud Box page clarification

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#864]
On the Nextcloud-Box page I found some things to clear up (https://nextcloud.com/box/):

> The software for the box as well as similar solutions are still being developed by Nextcloud contributors. You can use the Ubuntu Snap image for easy installation on small and large devices that already have an operating system. Alternatively you could use the NextcloudPi image, a full operating system aimed at the Raspberry Pi and other boards.

- it sounds like you could use Ubuntu snap on any system. Is this true? Or do you need Ubuntu?
- Nextcloud-pi, I'd rather write "a fully pre-configured operating system", it is not an operating system itself.

**Comment by MariusBluem** [comment]
- Snap is a standard (https://snapcraft.io) you can use on other Linux-based OSes too (SUSE, Debian, RedHat). We test the snap against Ubuntu, but I see no reason why it should not run on Debian for example :)

- Mind open a PR for this wording change (Nextcloud Pi)?
