### ISSUE TITLE
Title tag on website doesn’t say »Nextcloud«, but is long and convoluted

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#865]
So instead of, say »Blog – Nextcloud« the title when you are on the blog is »The latest updates &#8211; The most popular self-hosted file share and collaboration platform«. That’s a bit strange really, as a slogan is supposed to go into the description but not into the title. Also makes it very annoying to navigate your tabs.

cc @jospoortvliet @nextcloud/website

**Comment by jospoortvliet** [comment]
The problem initially was that some pages said "Nextcloud - Nextcloud" which also doesn't help too much. I don't feel like we should spend time fixing this now- better for the new website where we can actually really control this.

**Comment by arnowelzel** [comment]
The title consists of the page title plus site title. Why not just changing the site title from "The most popular self-hosted file share and collaboration platform" to "Nextcloud"? This is just a setting in the backend.

**Comment by jospoortvliet** [comment]
> The title consists of the page title plus site title. Why not just changing the site title from "The most popular self-hosted file share and collaboration platform" to "Nextcloud"? This is just a setting in the backend.
Because then some pages says "Nextcloud - Nextcloud". I haven't been able to figure out why, but - ok. Will move to Nextcloud again.

Done...
