### ISSUE TITLE
Nextcloud BEST Apps: How to edit the rights of each user or group.

### ISSUE THREAD

**Issue by newbie7777** [nextcloud/nextcloud.com#873]
Hello friends, I like it very much Nextcloud, an extremely powerful system and very easy to work with.

I have a problem with the rights of groups and users, i use the deck module. Users are not allowed to edit and manage but can be removed from a task by themselves.
Where can I give rights to groups and people, such as limiting editing and removal? :+1:  :)

**Comment by tflidd** [comment]
This is a repository for the nextcloud.com homepage. For general support questions, please ask at https://help.nextcloud.com. In case you found a bug, you can directly report it on the bugtracker for deck: https://github.com/nextcloud/deck/issues. In doubt, ask in the forum (first link) first.
