### ISSUE TITLE
Flag icons are pixelated on high-res displays

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#898]
The flag icons in the top right are a bit pixelated and look outdated.

We could instead use these SVGs: http://flag-icon-css.lip.is

cc @jospoortvliet @skjnldsv what do you think?

**Comment by skjnldsv** [comment]
Okay for me

**Comment by jospoortvliet** [comment]
fixed with different flags. Yes, we can move to another flag, again :dagger: :rage:
