### ISSUE TITLE
/conference should link to /conf

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud.com#902]
When accessing https://nextcloud.com/conference it should at least provide a link to the this years conference page at https://nextcloud.com/conf

@jospoortvliet

**Comment by juliushaertl** [comment]
Ah sorry, I was missing the content of /conference is about showing stuff at other conferences. I would probably change that url and just redirect /conference to /conf.

**Comment by jospoortvliet** [comment]
I added a redirect of /conference to /conf - the other redirect was Wordpress trying to smartly figure out what you could have meant and guessing 'conference-program'...
