### ISSUE TITLE
SSL cert for download.nextcloud.com has expired

### ISSUE THREAD

**Issue by realies** [nextcloud/nextcloud.com#914]
People on the IRC channel are reporting they can't get to anything from the `download.nextcloud.com` domain due to the SSL certificate being expired. Let me know if you need any help automating the renewal.

**Comment by Justintime50** [comment]
I'm glad you reported this. Hopped on just now to do so. It's definitely down.

**Comment by realies** [comment]
/offtopic @Justintime50, I think I just broke your Nextcloud install. No need for links in the footer IMO.

**Comment by MariusBluem** [comment]
Thanks for your report. I‘ve forwarded this to our infrastructure team, and we will keep you updated about this issue.

**Comment by MorrisJobke** [comment]
Fixed ... was a hiccup in certbot :/ Sorry for the mess.
