### ISSUE TITLE
German text is partly hidden

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#929]
On the [Enterprise](https://nextcloud.com/de/enterprise/) page  the german introduction text is hidden behind the main page content:

![enterprise](https://user-images.githubusercontent.com/1869584/43989921-93a5a640-9d53-11e8-824d-886efcc40bd8.png)

**Comment by jospoortvliet** [comment]
Fixed by removing 'Erhalte' ;-)
