### ISSUE TITLE
You have javascript disabled

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/nextcloud.com#931]
https://nextcloud.com/de/partners/ shows the "You have javascript disabled." message all the time. I tested it with FF and Chromium on Ubuntu. The message is shown with JS enabled.

**Comment by eFrane** [comment]
Also true for Safari Mobile.

**Comment by jospoortvliet** [comment]
Thanks, fixed!

**Comment by t-markmann** [comment]
Please re-open: this seems to happen on every /de page. 
Have a look at https://nextcloud.com/de/files/ or https://nextcloud.com/de/federation/
Tested in Firefox & Chrome with disabled browser add-ons. Other pages without /de work fine :-)
