### ISSUE TITLE
Drop shadow missing on top and left of main image

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#956]
The main image has the drop shadow strangely cut off – it only exists in the top left corner:
![](https://nextcloud.com/wp-content/themes/next/assets/img/home/top-banner@2x.png)

I guess this was done when minifying? @nextcloud/website Do we still have the original picture? (Also, the KDE mouse pointer we could remove?)

**Comment by jospoortvliet** [comment]
Ah, I have an XCF of this. I can also update the screenshot to 14...

**Comment by jospoortvliet** [comment]
Ok, thought its a big improvement so I deployed it :see_no_evil:

**Comment by jancborchardt** [comment]
Yes, good stuff! :+1:
