### ISSUE TITLE
Nextcloud security scan version number + X-Frame-options error

### ISSUE THREAD

**Issue by danger89** [nextcloud/nextcloud.com#968]
Hi,

I upgraded towards the latest stable version: Nextcloud 14.0.1

The Nextcloud Security Scan however reports I'm still using an old version (which is incorrect):
```
Running Nextcloud 13.0.1.1

NOT on latest patch level
```

Furthermore, the X-Frame-Options check fails as well during the scan.
![image](https://user-images.githubusercontent.com/628926/46617022-0e0c2580-cb1c-11e8-9407-c64a5ddc6686.png)

While in fact the header seems just be fine!
See:
https://securityheaders.com/?q=cloud.melroy.org&followRedirects=on

Kind regards,
Melroy

**Comment by jospoortvliet** [comment]
You might have to simply re-scan, see the date of the scan of your server.
