### ISSUE TITLE
Images in blog post either too small, or overflowing horizontally

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud.com#975]
I was reading the [blog post about integration with Rocket.Chat](https://nextcloud.com/blog/rocket.chat-and-nextcloud-announce-partnership-and-integration/) and the images are displayed strangely.

Either too small (container is really not needed):
![screenshot_20181010-163331](https://user-images.githubusercontent.com/925062/47156411-60510180-d2e7-11e8-8c95-6dc730a7d38b.png)

Or totally overflowing:
![screenshot_20181010-163336](https://user-images.githubusercontent.com/925062/47156410-60510180-d2e7-11e8-9c69-95ec8f54b15e.png)

To fix the overflowing, we should limit the width:
```
p img {
    max-width: 100%;
}
```

And for the `.thumbnail` class, I suggest this style modification:
```
.thumbnail {
    margin: 0;
    border: none;
    width: calc(100% + 30px) !important; /* account for double page margin */
    padding: 0;
    padding-bottom: 1em;
}

.thumbnail img {
    margin: 0 -15px; /* cancel out page margin */
}
```

Direct comparison:
![screenshot from 2018-10-18 15-21-02](https://user-images.githubusercontent.com/925062/47157371-7790ee80-d2e9-11e8-869b-ae99ca49d46b.png)

cc @nextcloud/website

**Comment by jospoortvliet** [comment]
addressed in https://github.com/nextcloud/nextcloud.com/pull/982
