### ISSUE TITLE
Feature Request: Link to Easy sign up with preselection

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/nextcloud.com#978]
It would be great if a provider could be preselected with a get parameter.

Example:

* `https://nextcloud.com/signup/?provider=webo.hosting`
* `https://nextcloud.com/signup/?provider=snowflakeOps`

This allows providers/users to refer/link directly to Nextcloud Easy sign up with a preselectet provider.

**Comment by jospoortvliet** [comment]
@skjnldsv what do you think, can you do that?

**Comment by skjnldsv** [comment]
Sure :)
