### ISSUE TITLE
HTML link issue in latest Nextcloud Client 2.5 blog post

### ISSUE THREAD

**Issue by noplanman** [nextcloud/nextcloud.com#999]
https://nextcloud.com/blog/nextcloud-desktop-client-2.5-is-out-with-end-to-end-encryption-new-login-flow-and-much-more/

Basically search the page for:
`Learn more ” rel=”noopener” target=”_blank”>end-to-end encryption and about encryption in Nextcloud in general.`

There's an HTML bug in there.

Are the blog posts open source somewhere too, to allow PRs for proofreading?

**Comment by jospoortvliet** [comment]
Fixed. The blogs are in wordpress- I can't really open that up easily... We do plan (for a long time, though) to move to a new blog platform that might make that possible!

Thanks!
